/* Generated by Yosys 0.33 (git sha1 2584903a060, clang++ 11.1.0 -fPIC -Os) */

module mk_fp32_bfloat16(CLK, RST_N, fp32_in_fp_in, bfloat16_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  input CLK;
  wire CLK;
  input RST_N;
  wire RST_N;
  output [15:0] bfloat16_out;
  wire [15:0] bfloat16_out;
  input [31:0] fp32_in_fp_in;
  wire [31:0] fp32_in_fp_in;
  wire \rg_bfloat16$D_IN[15] ;
  wire \rg_fp32[0] ;
  wire \rg_fp32[10] ;
  wire \rg_fp32[11] ;
  wire \rg_fp32[12] ;
  wire \rg_fp32[13] ;
  wire \rg_fp32[14] ;
  wire \rg_fp32[15] ;
  wire \rg_fp32[16] ;
  wire \rg_fp32[17] ;
  wire \rg_fp32[18] ;
  wire \rg_fp32[19] ;
  wire \rg_fp32[1] ;
  wire \rg_fp32[20] ;
  wire \rg_fp32[21] ;
  wire \rg_fp32[22] ;
  wire \rg_fp32[23] ;
  wire \rg_fp32[24] ;
  wire \rg_fp32[25] ;
  wire \rg_fp32[26] ;
  wire \rg_fp32[27] ;
  wire \rg_fp32[28] ;
  wire \rg_fp32[29] ;
  wire \rg_fp32[2] ;
  wire \rg_fp32[30] ;
  wire \rg_fp32[3] ;
  wire \rg_fp32[4] ;
  wire \rg_fp32[5] ;
  wire \rg_fp32[6] ;
  wire \rg_fp32[7] ;
  wire \rg_fp32[8] ;
  wire \rg_fp32[9] ;
  sky130_fd_sc_hd__or4_2 _171_ (
    .A(\rg_fp32[5] ),
    .B(\rg_fp32[4] ),
    .C(\rg_fp32[7] ),
    .D(\rg_fp32[6] ),
    .X(_048_)
  );
  sky130_fd_sc_hd__or4_2 _172_ (
    .A(\rg_fp32[1] ),
    .B(\rg_fp32[0] ),
    .C(\rg_fp32[3] ),
    .D(\rg_fp32[2] ),
    .X(_049_)
  );
  sky130_fd_sc_hd__or4_2 _173_ (
    .A(\rg_fp32[9] ),
    .B(\rg_fp32[8] ),
    .C(\rg_fp32[11] ),
    .D(\rg_fp32[10] ),
    .X(_050_)
  );
  sky130_fd_sc_hd__or3_2 _174_ (
    .A(\rg_fp32[13] ),
    .B(\rg_fp32[12] ),
    .C(\rg_fp32[14] ),
    .X(_051_)
  );
  sky130_fd_sc_hd__or4_2 _175_ (
    .A(_048_),
    .B(_049_),
    .C(_050_),
    .D(_051_),
    .X(_052_)
  );
  sky130_fd_sc_hd__or4_2 _176_ (
    .A(\rg_fp32[18] ),
    .B(\rg_fp32[21] ),
    .C(\rg_fp32[20] ),
    .D(\rg_fp32[22] ),
    .X(_053_)
  );
  sky130_fd_sc_hd__or4_2 _177_ (
    .A(\rg_fp32[15] ),
    .B(\rg_fp32[17] ),
    .C(\rg_fp32[16] ),
    .D(\rg_fp32[19] ),
    .X(_054_)
  );
  sky130_fd_sc_hd__nor3_2 _178_ (
    .A(_052_),
    .B(_053_),
    .C(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__and4_2 _179_ (
    .A(\rg_fp32[24] ),
    .B(\rg_fp32[26] ),
    .C(\rg_fp32[25] ),
    .D(\rg_fp32[27] ),
    .X(_056_)
  );
  sky130_fd_sc_hd__and2_2 _180_ (
    .A(\rg_fp32[28] ),
    .B(\rg_fp32[29] ),
    .X(_057_)
  );
  sky130_fd_sc_hd__and4_2 _181_ (
    .A(\rg_fp32[23] ),
    .B(\rg_fp32[30] ),
    .C(_056_),
    .D(_057_),
    .X(_058_)
  );
  sky130_fd_sc_hd__o21a_2 _182_ (
    .A1(\rg_fp32[0] ),
    .A2(_055_),
    .B1(_058_),
    .X(_059_)
  );
  sky130_fd_sc_hd__or4_2 _183_ (
    .A(\rg_fp32[27] ),
    .B(\rg_fp32[28] ),
    .C(\rg_fp32[29] ),
    .D(\rg_fp32[30] ),
    .X(_060_)
  );
  sky130_fd_sc_hd__or4_2 _184_ (
    .A(\rg_fp32[24] ),
    .B(\rg_fp32[23] ),
    .C(\rg_fp32[26] ),
    .D(\rg_fp32[25] ),
    .X(_061_)
  );
  sky130_fd_sc_hd__nor2_2 _185_ (
    .A(_060_),
    .B(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__or2_2 _186_ (
    .A(_062_),
    .B(_058_),
    .X(_063_)
  );
  sky130_fd_sc_hd__a21boi_2 _187_ (
    .A1(_063_),
    .A2(_055_),
    .B1_N(RST_N),
    .Y(_064_)
  );
  sky130_fd_sc_hd__and2b_2 _188_ (
    .A_N(_059_),
    .B(_064_),
    .X(_065_)
  );
  sky130_fd_sc_hd__and2_2 _189_ (
    .A(\rg_fp32[15] ),
    .B(\rg_fp32[16] ),
    .X(_066_)
  );
  sky130_fd_sc_hd__nand2_2 _190_ (
    .A(\rg_fp32[17] ),
    .B(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__or2_2 _191_ (
    .A(\rg_fp32[17] ),
    .B(_066_),
    .X(_068_)
  );
  sky130_fd_sc_hd__and3_2 _192_ (
    .A(_065_),
    .B(_067_),
    .C(_068_),
    .X(_069_)
  );
  sky130_fd_sc_hd__buf_1 _193_ (
    .A(_069_),
    .X(_010_)
  );
  sky130_fd_sc_hd__nand3_2 _194_ (
    .A(\rg_fp32[17] ),
    .B(\rg_fp32[18] ),
    .C(_066_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__a31o_2 _195_ (
    .A1(\rg_fp32[15] ),
    .A2(\rg_fp32[17] ),
    .A3(\rg_fp32[16] ),
    .B1(\rg_fp32[18] ),
    .X(_071_)
  );
  sky130_fd_sc_hd__and3_2 _196_ (
    .A(_065_),
    .B(_070_),
    .C(_071_),
    .X(_072_)
  );
  sky130_fd_sc_hd__buf_1 _197_ (
    .A(_072_),
    .X(_011_)
  );
  sky130_fd_sc_hd__inv_2 _198_ (
    .A(\rg_fp32[19] ),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_2 _199_ (
    .A(_073_),
    .B(_070_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__or2_2 _200_ (
    .A(_073_),
    .B(_070_),
    .X(_075_)
  );
  sky130_fd_sc_hd__and3_2 _201_ (
    .A(_065_),
    .B(_074_),
    .C(_075_),
    .X(_076_)
  );
  sky130_fd_sc_hd__buf_1 _202_ (
    .A(_076_),
    .X(_012_)
  );
  sky130_fd_sc_hd__and4_2 _203_ (
    .A(\rg_fp32[17] ),
    .B(\rg_fp32[16] ),
    .C(\rg_fp32[19] ),
    .D(\rg_fp32[18] ),
    .X(_077_)
  );
  sky130_fd_sc_hd__buf_1 _204_ (
    .A(_077_),
    .X(_078_)
  );
  sky130_fd_sc_hd__o41a_2 _205_ (
    .A1(_048_),
    .A2(_049_),
    .A3(_050_),
    .A4(_051_),
    .B1(\rg_fp32[15] ),
    .X(_079_)
  );
  sky130_fd_sc_hd__buf_1 _206_ (
    .A(_079_),
    .X(_080_)
  );
  sky130_fd_sc_hd__a21oi_2 _207_ (
    .A1(_078_),
    .A2(_080_),
    .B1(\rg_fp32[20] ),
    .Y(_081_)
  );
  sky130_fd_sc_hd__and3_2 _208_ (
    .A(\rg_fp32[20] ),
    .B(_078_),
    .C(_080_),
    .X(_082_)
  );
  sky130_fd_sc_hd__nor2b_2 _209_ (
    .A(_052_),
    .B_N(_066_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _210_ (
    .A1_N(_081_),
    .A2_N(_082_),
    .B1(_083_),
    .B2(_078_),
    .X(_084_)
  );
  sky130_fd_sc_hd__nand3_2 _211_ (
    .A(\rg_fp32[20] ),
    .B(_083_),
    .C(_078_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__and3_2 _212_ (
    .A(_065_),
    .B(_084_),
    .C(_085_),
    .X(_086_)
  );
  sky130_fd_sc_hd__buf_1 _213_ (
    .A(_086_),
    .X(_013_)
  );
  sky130_fd_sc_hd__a31o_2 _214_ (
    .A1(\rg_fp32[20] ),
    .A2(_083_),
    .A3(_078_),
    .B1(\rg_fp32[21] ),
    .X(_087_)
  );
  sky130_fd_sc_hd__and3_2 _215_ (
    .A(\rg_fp32[21] ),
    .B(\rg_fp32[20] ),
    .C(_077_),
    .X(_088_)
  );
  sky130_fd_sc_hd__nand2_2 _216_ (
    .A(_083_),
    .B(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__a21o_2 _217_ (
    .A1(_087_),
    .A2(_089_),
    .B1(_082_),
    .X(_090_)
  );
  sky130_fd_sc_hd__nand2_2 _218_ (
    .A(_080_),
    .B(_088_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__and3_2 _219_ (
    .A(_065_),
    .B(_090_),
    .C(_091_),
    .X(_092_)
  );
  sky130_fd_sc_hd__buf_1 _220_ (
    .A(_092_),
    .X(_014_)
  );
  sky130_fd_sc_hd__and2_2 _221_ (
    .A(RST_N),
    .B(fp32_in_fp_in[0]),
    .X(_093_)
  );
  sky130_fd_sc_hd__buf_1 _222_ (
    .A(_093_),
    .X(_015_)
  );
  sky130_fd_sc_hd__and2_2 _223_ (
    .A(RST_N),
    .B(fp32_in_fp_in[1]),
    .X(_094_)
  );
  sky130_fd_sc_hd__buf_1 _224_ (
    .A(_094_),
    .X(_016_)
  );
  sky130_fd_sc_hd__and2_2 _225_ (
    .A(RST_N),
    .B(fp32_in_fp_in[2]),
    .X(_095_)
  );
  sky130_fd_sc_hd__buf_1 _226_ (
    .A(_095_),
    .X(_017_)
  );
  sky130_fd_sc_hd__and2_2 _227_ (
    .A(RST_N),
    .B(fp32_in_fp_in[3]),
    .X(_096_)
  );
  sky130_fd_sc_hd__buf_1 _228_ (
    .A(_096_),
    .X(_018_)
  );
  sky130_fd_sc_hd__and2_2 _229_ (
    .A(RST_N),
    .B(fp32_in_fp_in[4]),
    .X(_097_)
  );
  sky130_fd_sc_hd__buf_1 _230_ (
    .A(_097_),
    .X(_019_)
  );
  sky130_fd_sc_hd__and2_2 _231_ (
    .A(RST_N),
    .B(fp32_in_fp_in[5]),
    .X(_098_)
  );
  sky130_fd_sc_hd__buf_1 _232_ (
    .A(_098_),
    .X(_020_)
  );
  sky130_fd_sc_hd__and2_2 _233_ (
    .A(RST_N),
    .B(fp32_in_fp_in[6]),
    .X(_099_)
  );
  sky130_fd_sc_hd__buf_1 _234_ (
    .A(_099_),
    .X(_021_)
  );
  sky130_fd_sc_hd__and2_2 _235_ (
    .A(RST_N),
    .B(fp32_in_fp_in[7]),
    .X(_100_)
  );
  sky130_fd_sc_hd__buf_1 _236_ (
    .A(_100_),
    .X(_022_)
  );
  sky130_fd_sc_hd__and2_2 _237_ (
    .A(RST_N),
    .B(fp32_in_fp_in[8]),
    .X(_101_)
  );
  sky130_fd_sc_hd__buf_1 _238_ (
    .A(_101_),
    .X(_023_)
  );
  sky130_fd_sc_hd__and2_2 _239_ (
    .A(RST_N),
    .B(fp32_in_fp_in[9]),
    .X(_102_)
  );
  sky130_fd_sc_hd__buf_1 _240_ (
    .A(_102_),
    .X(_024_)
  );
  sky130_fd_sc_hd__and2_2 _241_ (
    .A(RST_N),
    .B(fp32_in_fp_in[10]),
    .X(_103_)
  );
  sky130_fd_sc_hd__buf_1 _242_ (
    .A(_103_),
    .X(_025_)
  );
  sky130_fd_sc_hd__and2_2 _243_ (
    .A(RST_N),
    .B(fp32_in_fp_in[11]),
    .X(_104_)
  );
  sky130_fd_sc_hd__buf_1 _244_ (
    .A(_104_),
    .X(_026_)
  );
  sky130_fd_sc_hd__and2_2 _245_ (
    .A(RST_N),
    .B(fp32_in_fp_in[12]),
    .X(_105_)
  );
  sky130_fd_sc_hd__buf_1 _246_ (
    .A(_105_),
    .X(_027_)
  );
  sky130_fd_sc_hd__and2_2 _247_ (
    .A(RST_N),
    .B(fp32_in_fp_in[13]),
    .X(_106_)
  );
  sky130_fd_sc_hd__buf_1 _248_ (
    .A(_106_),
    .X(_028_)
  );
  sky130_fd_sc_hd__and2_2 _249_ (
    .A(RST_N),
    .B(fp32_in_fp_in[14]),
    .X(_107_)
  );
  sky130_fd_sc_hd__buf_1 _250_ (
    .A(_107_),
    .X(_029_)
  );
  sky130_fd_sc_hd__and2_2 _251_ (
    .A(RST_N),
    .B(fp32_in_fp_in[15]),
    .X(_108_)
  );
  sky130_fd_sc_hd__buf_1 _252_ (
    .A(_108_),
    .X(_030_)
  );
  sky130_fd_sc_hd__and2_2 _253_ (
    .A(RST_N),
    .B(fp32_in_fp_in[16]),
    .X(_109_)
  );
  sky130_fd_sc_hd__buf_1 _254_ (
    .A(_109_),
    .X(_031_)
  );
  sky130_fd_sc_hd__and2_2 _255_ (
    .A(RST_N),
    .B(fp32_in_fp_in[17]),
    .X(_110_)
  );
  sky130_fd_sc_hd__buf_1 _256_ (
    .A(_110_),
    .X(_032_)
  );
  sky130_fd_sc_hd__and2_2 _257_ (
    .A(RST_N),
    .B(fp32_in_fp_in[18]),
    .X(_111_)
  );
  sky130_fd_sc_hd__buf_1 _258_ (
    .A(_111_),
    .X(_033_)
  );
  sky130_fd_sc_hd__and2_2 _259_ (
    .A(RST_N),
    .B(fp32_in_fp_in[19]),
    .X(_112_)
  );
  sky130_fd_sc_hd__buf_1 _260_ (
    .A(_112_),
    .X(_034_)
  );
  sky130_fd_sc_hd__and2_2 _261_ (
    .A(RST_N),
    .B(fp32_in_fp_in[20]),
    .X(_113_)
  );
  sky130_fd_sc_hd__buf_1 _262_ (
    .A(_113_),
    .X(_035_)
  );
  sky130_fd_sc_hd__and2_2 _263_ (
    .A(RST_N),
    .B(fp32_in_fp_in[21]),
    .X(_114_)
  );
  sky130_fd_sc_hd__buf_1 _264_ (
    .A(_114_),
    .X(_036_)
  );
  sky130_fd_sc_hd__and2_2 _265_ (
    .A(RST_N),
    .B(fp32_in_fp_in[22]),
    .X(_115_)
  );
  sky130_fd_sc_hd__buf_1 _266_ (
    .A(_115_),
    .X(_037_)
  );
  sky130_fd_sc_hd__and2_2 _267_ (
    .A(RST_N),
    .B(fp32_in_fp_in[23]),
    .X(_116_)
  );
  sky130_fd_sc_hd__buf_1 _268_ (
    .A(_116_),
    .X(_038_)
  );
  sky130_fd_sc_hd__and2_2 _269_ (
    .A(RST_N),
    .B(fp32_in_fp_in[24]),
    .X(_117_)
  );
  sky130_fd_sc_hd__buf_1 _270_ (
    .A(_117_),
    .X(_039_)
  );
  sky130_fd_sc_hd__and2_2 _271_ (
    .A(RST_N),
    .B(fp32_in_fp_in[25]),
    .X(_118_)
  );
  sky130_fd_sc_hd__buf_1 _272_ (
    .A(_118_),
    .X(_040_)
  );
  sky130_fd_sc_hd__and2_2 _273_ (
    .A(RST_N),
    .B(fp32_in_fp_in[26]),
    .X(_119_)
  );
  sky130_fd_sc_hd__buf_1 _274_ (
    .A(_119_),
    .X(_041_)
  );
  sky130_fd_sc_hd__and2_2 _275_ (
    .A(RST_N),
    .B(fp32_in_fp_in[27]),
    .X(_120_)
  );
  sky130_fd_sc_hd__buf_1 _276_ (
    .A(_120_),
    .X(_042_)
  );
  sky130_fd_sc_hd__and2_2 _277_ (
    .A(RST_N),
    .B(fp32_in_fp_in[28]),
    .X(_121_)
  );
  sky130_fd_sc_hd__buf_1 _278_ (
    .A(_121_),
    .X(_043_)
  );
  sky130_fd_sc_hd__and2_2 _279_ (
    .A(RST_N),
    .B(fp32_in_fp_in[29]),
    .X(_122_)
  );
  sky130_fd_sc_hd__buf_1 _280_ (
    .A(_122_),
    .X(_044_)
  );
  sky130_fd_sc_hd__and2_2 _281_ (
    .A(RST_N),
    .B(fp32_in_fp_in[30]),
    .X(_123_)
  );
  sky130_fd_sc_hd__buf_1 _282_ (
    .A(_123_),
    .X(_045_)
  );
  sky130_fd_sc_hd__and2_2 _283_ (
    .A(RST_N),
    .B(fp32_in_fp_in[31]),
    .X(_124_)
  );
  sky130_fd_sc_hd__buf_1 _284_ (
    .A(_124_),
    .X(_046_)
  );
  sky130_fd_sc_hd__buf_1 _285_ (
    .A(_059_),
    .X(_125_)
  );
  sky130_fd_sc_hd__inv_2 _286_ (
    .A(\rg_fp32[22] ),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nor2_2 _287_ (
    .A(_126_),
    .B(_091_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__and4bb_2 _288_ (
    .A_N(_126_),
    .B_N(_052_),
    .C(_066_),
    .D(_088_),
    .X(_128_)
  );
  sky130_fd_sc_hd__xnor2_2 _289_ (
    .A(\rg_fp32[23] ),
    .B(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__xnor2_2 _290_ (
    .A(_127_),
    .B(_129_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__a21boi_2 _291_ (
    .A1(_062_),
    .A2(_055_),
    .B1_N(RST_N),
    .Y(_131_)
  );
  sky130_fd_sc_hd__buf_1 _292_ (
    .A(_131_),
    .X(_132_)
  );
  sky130_fd_sc_hd__o21a_2 _293_ (
    .A1(_125_),
    .A2(_130_),
    .B1(_132_),
    .X(_047_)
  );
  sky130_fd_sc_hd__and2_2 _294_ (
    .A(\rg_fp32[23] ),
    .B(_128_),
    .X(_133_)
  );
  sky130_fd_sc_hd__buf_1 _295_ (
    .A(_133_),
    .X(_134_)
  );
  sky130_fd_sc_hd__and2_2 _296_ (
    .A(\rg_fp32[23] ),
    .B(\rg_fp32[22] ),
    .X(_135_)
  );
  sky130_fd_sc_hd__and4_2 _297_ (
    .A(\rg_fp32[21] ),
    .B(\rg_fp32[20] ),
    .C(_078_),
    .D(_135_),
    .X(_136_)
  );
  sky130_fd_sc_hd__and2_2 _298_ (
    .A(_079_),
    .B(_136_),
    .X(_137_)
  );
  sky130_fd_sc_hd__nand3_2 _299_ (
    .A(\rg_fp32[24] ),
    .B(_080_),
    .C(_136_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__o21ai_2 _300_ (
    .A1(\rg_fp32[24] ),
    .A2(_137_),
    .B1(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__xnor2_2 _301_ (
    .A(_134_),
    .B(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__o21a_2 _302_ (
    .A1(_125_),
    .A2(_140_),
    .B1(_132_),
    .X(_000_)
  );
  sky130_fd_sc_hd__xor2_2 _303_ (
    .A(\rg_fp32[25] ),
    .B(_138_),
    .X(_141_)
  );
  sky130_fd_sc_hd__and3_2 _304_ (
    .A(\rg_fp32[24] ),
    .B(_083_),
    .C(_136_),
    .X(_142_)
  );
  sky130_fd_sc_hd__xnor2_2 _305_ (
    .A(_141_),
    .B(_142_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__o21a_2 _306_ (
    .A1(_125_),
    .A2(_143_),
    .B1(_132_),
    .X(_001_)
  );
  sky130_fd_sc_hd__and3_2 _307_ (
    .A(\rg_fp32[24] ),
    .B(\rg_fp32[26] ),
    .C(\rg_fp32[25] ),
    .X(_144_)
  );
  sky130_fd_sc_hd__a41o_2 _308_ (
    .A1(\rg_fp32[24] ),
    .A2(\rg_fp32[25] ),
    .A3(_079_),
    .A4(_136_),
    .B1(\rg_fp32[26] ),
    .X(_145_)
  );
  sky130_fd_sc_hd__a21bo_2 _309_ (
    .A1(_144_),
    .A2(_137_),
    .B1_N(_145_),
    .X(_146_)
  );
  sky130_fd_sc_hd__a21oi_2 _310_ (
    .A1(\rg_fp32[25] ),
    .A2(_142_),
    .B1(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a31o_2 _311_ (
    .A1(\rg_fp32[25] ),
    .A2(_142_),
    .A3(_146_),
    .B1(_125_),
    .X(_148_)
  );
  sky130_fd_sc_hd__o21a_2 _312_ (
    .A1(_147_),
    .A2(_148_),
    .B1(_132_),
    .X(_002_)
  );
  sky130_fd_sc_hd__a21oi_2 _313_ (
    .A1(_144_),
    .A2(_137_),
    .B1(\rg_fp32[27] ),
    .Y(_149_)
  );
  sky130_fd_sc_hd__and3_2 _314_ (
    .A(_056_),
    .B(_079_),
    .C(_136_),
    .X(_150_)
  );
  sky130_fd_sc_hd__o211a_2 _315_ (
    .A1(_149_),
    .A2(_150_),
    .B1(_144_),
    .C1(_134_),
    .X(_151_)
  );
  sky130_fd_sc_hd__a211oi_2 _316_ (
    .A1(_144_),
    .A2(_134_),
    .B1(_149_),
    .C1(_150_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__o31a_2 _317_ (
    .A1(_125_),
    .A2(_151_),
    .A3(_152_),
    .B1(_131_),
    .X(_003_)
  );
  sky130_fd_sc_hd__xnor2_2 _318_ (
    .A(\rg_fp32[28] ),
    .B(_150_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a21oi_2 _319_ (
    .A1(_056_),
    .A2(_134_),
    .B1(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a31o_2 _320_ (
    .A1(_056_),
    .A2(_134_),
    .A3(_153_),
    .B1(_059_),
    .X(_155_)
  );
  sky130_fd_sc_hd__o21a_2 _321_ (
    .A1(_154_),
    .A2(_155_),
    .B1(_132_),
    .X(_004_)
  );
  sky130_fd_sc_hd__a21oi_2 _322_ (
    .A1(\rg_fp32[28] ),
    .A2(_150_),
    .B1(\rg_fp32[29] ),
    .Y(_156_)
  );
  sky130_fd_sc_hd__and4_2 _323_ (
    .A(_056_),
    .B(_057_),
    .C(_079_),
    .D(_136_),
    .X(_157_)
  );
  sky130_fd_sc_hd__and4_2 _324_ (
    .A(\rg_fp32[23] ),
    .B(\rg_fp32[28] ),
    .C(_056_),
    .D(_128_),
    .X(_158_)
  );
  sky130_fd_sc_hd__nor3_2 _325_ (
    .A(_156_),
    .B(_157_),
    .C(_158_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__o21a_2 _326_ (
    .A1(_156_),
    .A2(_157_),
    .B1(_158_),
    .X(_160_)
  );
  sky130_fd_sc_hd__o31a_2 _327_ (
    .A1(_125_),
    .A2(_159_),
    .A3(_160_),
    .B1(_131_),
    .X(_005_)
  );
  sky130_fd_sc_hd__xnor2_2 _328_ (
    .A(\rg_fp32[30] ),
    .B(_157_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__a21oi_2 _329_ (
    .A1(\rg_fp32[29] ),
    .A2(_158_),
    .B1(_161_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__a31o_2 _330_ (
    .A1(\rg_fp32[29] ),
    .A2(_158_),
    .A3(_161_),
    .B1(_059_),
    .X(_163_)
  );
  sky130_fd_sc_hd__o21a_2 _331_ (
    .A1(_162_),
    .A2(_163_),
    .B1(_132_),
    .X(_006_)
  );
  sky130_fd_sc_hd__nor2_2 _332_ (
    .A(\rg_fp32[16] ),
    .B(_080_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand2_2 _333_ (
    .A(\rg_fp32[0] ),
    .B(_058_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__o21ai_2 _334_ (
    .A1(_066_),
    .A2(_164_),
    .B1(_165_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__and2_2 _335_ (
    .A(_064_),
    .B(_166_),
    .X(_167_)
  );
  sky130_fd_sc_hd__buf_1 _336_ (
    .A(_167_),
    .X(_007_)
  );
  sky130_fd_sc_hd__o211a_2 _337_ (
    .A1(_083_),
    .A2(_080_),
    .B1(_088_),
    .C1(_165_),
    .X(_168_)
  );
  sky130_fd_sc_hd__o21ai_2 _338_ (
    .A1(\rg_fp32[22] ),
    .A2(_168_),
    .B1(_064_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__a21oi_2 _339_ (
    .A1(\rg_fp32[22] ),
    .A2(_168_),
    .B1(_169_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__and2_2 _340_ (
    .A(RST_N),
    .B(\rg_bfloat16$D_IN[15] ),
    .X(_170_)
  );
  sky130_fd_sc_hd__buf_1 _341_ (
    .A(_170_),
    .X(_009_)
  );
  sky130_fd_sc_hd__dfxtp_2 _342_ (
    .CLK(CLK),
    .D(_010_),
    .Q(bfloat16_out[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _343_ (
    .CLK(CLK),
    .D(_011_),
    .Q(bfloat16_out[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _344_ (
    .CLK(CLK),
    .D(_012_),
    .Q(bfloat16_out[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _345_ (
    .CLK(CLK),
    .D(_013_),
    .Q(bfloat16_out[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _346_ (
    .CLK(CLK),
    .D(_014_),
    .Q(bfloat16_out[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _347_ (
    .CLK(CLK),
    .D(_015_),
    .Q(\rg_fp32[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _348_ (
    .CLK(CLK),
    .D(_016_),
    .Q(\rg_fp32[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _349_ (
    .CLK(CLK),
    .D(_017_),
    .Q(\rg_fp32[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _350_ (
    .CLK(CLK),
    .D(_018_),
    .Q(\rg_fp32[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _351_ (
    .CLK(CLK),
    .D(_019_),
    .Q(\rg_fp32[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _352_ (
    .CLK(CLK),
    .D(_020_),
    .Q(\rg_fp32[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _353_ (
    .CLK(CLK),
    .D(_021_),
    .Q(\rg_fp32[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _354_ (
    .CLK(CLK),
    .D(_022_),
    .Q(\rg_fp32[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _355_ (
    .CLK(CLK),
    .D(_023_),
    .Q(\rg_fp32[8] )
  );
  sky130_fd_sc_hd__dfxtp_2 _356_ (
    .CLK(CLK),
    .D(_024_),
    .Q(\rg_fp32[9] )
  );
  sky130_fd_sc_hd__dfxtp_2 _357_ (
    .CLK(CLK),
    .D(_025_),
    .Q(\rg_fp32[10] )
  );
  sky130_fd_sc_hd__dfxtp_2 _358_ (
    .CLK(CLK),
    .D(_026_),
    .Q(\rg_fp32[11] )
  );
  sky130_fd_sc_hd__dfxtp_2 _359_ (
    .CLK(CLK),
    .D(_027_),
    .Q(\rg_fp32[12] )
  );
  sky130_fd_sc_hd__dfxtp_2 _360_ (
    .CLK(CLK),
    .D(_028_),
    .Q(\rg_fp32[13] )
  );
  sky130_fd_sc_hd__dfxtp_2 _361_ (
    .CLK(CLK),
    .D(_029_),
    .Q(\rg_fp32[14] )
  );
  sky130_fd_sc_hd__dfxtp_2 _362_ (
    .CLK(CLK),
    .D(_030_),
    .Q(\rg_fp32[15] )
  );
  sky130_fd_sc_hd__dfxtp_2 _363_ (
    .CLK(CLK),
    .D(_031_),
    .Q(\rg_fp32[16] )
  );
  sky130_fd_sc_hd__dfxtp_2 _364_ (
    .CLK(CLK),
    .D(_032_),
    .Q(\rg_fp32[17] )
  );
  sky130_fd_sc_hd__dfxtp_2 _365_ (
    .CLK(CLK),
    .D(_033_),
    .Q(\rg_fp32[18] )
  );
  sky130_fd_sc_hd__dfxtp_2 _366_ (
    .CLK(CLK),
    .D(_034_),
    .Q(\rg_fp32[19] )
  );
  sky130_fd_sc_hd__dfxtp_2 _367_ (
    .CLK(CLK),
    .D(_035_),
    .Q(\rg_fp32[20] )
  );
  sky130_fd_sc_hd__dfxtp_2 _368_ (
    .CLK(CLK),
    .D(_036_),
    .Q(\rg_fp32[21] )
  );
  sky130_fd_sc_hd__dfxtp_2 _369_ (
    .CLK(CLK),
    .D(_037_),
    .Q(\rg_fp32[22] )
  );
  sky130_fd_sc_hd__dfxtp_2 _370_ (
    .CLK(CLK),
    .D(_038_),
    .Q(\rg_fp32[23] )
  );
  sky130_fd_sc_hd__dfxtp_2 _371_ (
    .CLK(CLK),
    .D(_039_),
    .Q(\rg_fp32[24] )
  );
  sky130_fd_sc_hd__dfxtp_2 _372_ (
    .CLK(CLK),
    .D(_040_),
    .Q(\rg_fp32[25] )
  );
  sky130_fd_sc_hd__dfxtp_2 _373_ (
    .CLK(CLK),
    .D(_041_),
    .Q(\rg_fp32[26] )
  );
  sky130_fd_sc_hd__dfxtp_2 _374_ (
    .CLK(CLK),
    .D(_042_),
    .Q(\rg_fp32[27] )
  );
  sky130_fd_sc_hd__dfxtp_2 _375_ (
    .CLK(CLK),
    .D(_043_),
    .Q(\rg_fp32[28] )
  );
  sky130_fd_sc_hd__dfxtp_2 _376_ (
    .CLK(CLK),
    .D(_044_),
    .Q(\rg_fp32[29] )
  );
  sky130_fd_sc_hd__dfxtp_2 _377_ (
    .CLK(CLK),
    .D(_045_),
    .Q(\rg_fp32[30] )
  );
  sky130_fd_sc_hd__dfxtp_2 _378_ (
    .CLK(CLK),
    .D(_046_),
    .Q(\rg_bfloat16$D_IN[15] )
  );
  sky130_fd_sc_hd__dfxtp_2 _379_ (
    .CLK(CLK),
    .D(_047_),
    .Q(bfloat16_out[7])
  );
  sky130_fd_sc_hd__dfxtp_2 _380_ (
    .CLK(CLK),
    .D(_000_),
    .Q(bfloat16_out[8])
  );
  sky130_fd_sc_hd__dfxtp_2 _381_ (
    .CLK(CLK),
    .D(_001_),
    .Q(bfloat16_out[9])
  );
  sky130_fd_sc_hd__dfxtp_2 _382_ (
    .CLK(CLK),
    .D(_002_),
    .Q(bfloat16_out[10])
  );
  sky130_fd_sc_hd__dfxtp_2 _383_ (
    .CLK(CLK),
    .D(_003_),
    .Q(bfloat16_out[11])
  );
  sky130_fd_sc_hd__dfxtp_2 _384_ (
    .CLK(CLK),
    .D(_004_),
    .Q(bfloat16_out[12])
  );
  sky130_fd_sc_hd__dfxtp_2 _385_ (
    .CLK(CLK),
    .D(_005_),
    .Q(bfloat16_out[13])
  );
  sky130_fd_sc_hd__dfxtp_2 _386_ (
    .CLK(CLK),
    .D(_006_),
    .Q(bfloat16_out[14])
  );
  sky130_fd_sc_hd__dfxtp_2 _387_ (
    .CLK(CLK),
    .D(_007_),
    .Q(bfloat16_out[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _388_ (
    .CLK(CLK),
    .D(_008_),
    .Q(bfloat16_out[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _389_ (
    .CLK(CLK),
    .D(_009_),
    .Q(bfloat16_out[15])
  );
endmodule
