/* Generated by Yosys 0.33 (git sha1 2584903a060, clang++ 11.1.0 -fPIC -Os) */

module mk_cfloat152_fp32(CLK, RST_N, cfloat152_in_cfloat_in, bias_in_bias, fp32_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  input CLK;
  wire CLK;
  input RST_N;
  wire RST_N;
  input [5:0] bias_in_bias;
  wire [5:0] bias_in_bias;
  input [7:0] cfloat152_in_cfloat_in;
  wire [7:0] cfloat152_in_cfloat_in;
  wire \fp32_mantissa__h323[21] ;
  wire \fp32_mantissa__h323[22] ;
  output [31:0] fp32_out;
  wire [31:0] fp32_out;
  wire \rg_bias[0] ;
  wire \rg_bias[1] ;
  wire \rg_bias[2] ;
  wire \rg_bias[3] ;
  wire \rg_bias[4] ;
  wire \rg_bias[5] ;
  wire \rg_cfloat152[2] ;
  wire \rg_cfloat152[3] ;
  wire \rg_cfloat152[4] ;
  wire \rg_cfloat152[5] ;
  wire \rg_cfloat152[6] ;
  wire \rg_cfloat152[7] ;
  sky130_fd_sc_hd__and2_2 _106_ (
    .A(RST_N),
    .B(\rg_cfloat152[7] ),
    .X(_066_)
  );
  sky130_fd_sc_hd__buf_1 _107_ (
    .A(_066_),
    .X(_000_)
  );
  sky130_fd_sc_hd__or3_2 _108_ (
    .A(\rg_cfloat152[5] ),
    .B(\rg_cfloat152[4] ),
    .C(\rg_cfloat152[6] ),
    .X(_067_)
  );
  sky130_fd_sc_hd__or3_2 _109_ (
    .A(\rg_cfloat152[3] ),
    .B(\rg_cfloat152[2] ),
    .C(_067_),
    .X(_068_)
  );
  sky130_fd_sc_hd__and3_2 _110_ (
    .A(RST_N),
    .B(\fp32_mantissa__h323[21] ),
    .C(_068_),
    .X(_069_)
  );
  sky130_fd_sc_hd__buf_1 _111_ (
    .A(_069_),
    .X(_001_)
  );
  sky130_fd_sc_hd__or2b_2 _112_ (
    .A(\rg_cfloat152[5] ),
    .B_N(\rg_bias[3] ),
    .X(_070_)
  );
  sky130_fd_sc_hd__xnor2_2 _113_ (
    .A(\rg_cfloat152[4] ),
    .B(\rg_bias[2] ),
    .Y(_071_)
  );
  sky130_fd_sc_hd__xnor2_2 _114_ (
    .A(\rg_cfloat152[3] ),
    .B(\rg_bias[1] ),
    .Y(_072_)
  );
  sky130_fd_sc_hd__or2b_2 _115_ (
    .A(\rg_cfloat152[2] ),
    .B_N(\rg_bias[0] ),
    .X(_073_)
  );
  sky130_fd_sc_hd__and2b_2 _116_ (
    .A_N(\rg_bias[1] ),
    .B(\rg_cfloat152[3] ),
    .X(_074_)
  );
  sky130_fd_sc_hd__a21o_2 _117_ (
    .A1(_072_),
    .A2(_073_),
    .B1(_074_),
    .X(_075_)
  );
  sky130_fd_sc_hd__or2b_2 _118_ (
    .A(\rg_bias[3] ),
    .B_N(\rg_cfloat152[5] ),
    .X(_076_)
  );
  sky130_fd_sc_hd__or2b_2 _119_ (
    .A(\rg_bias[2] ),
    .B_N(\rg_cfloat152[4] ),
    .X(_077_)
  );
  sky130_fd_sc_hd__nand2_2 _120_ (
    .A(_076_),
    .B(_077_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__a21o_2 _121_ (
    .A1(_071_),
    .A2(_075_),
    .B1(_078_),
    .X(_079_)
  );
  sky130_fd_sc_hd__and2b_2 _122_ (
    .A_N(\rg_cfloat152[6] ),
    .B(\rg_bias[4] ),
    .X(_080_)
  );
  sky130_fd_sc_hd__and2b_2 _123_ (
    .A_N(\rg_bias[4] ),
    .B(\rg_cfloat152[6] ),
    .X(_081_)
  );
  sky130_fd_sc_hd__nor2_2 _124_ (
    .A(_080_),
    .B(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand3_2 _125_ (
    .A(_070_),
    .B(_079_),
    .C(_082_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__a21o_2 _126_ (
    .A1(_070_),
    .A2(_079_),
    .B1(_082_),
    .X(_084_)
  );
  sky130_fd_sc_hd__nand2_2 _127_ (
    .A(_076_),
    .B(_070_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__or2b_2 _128_ (
    .A(\rg_bias[0] ),
    .B_N(\rg_cfloat152[2] ),
    .X(_086_)
  );
  sky130_fd_sc_hd__and2_2 _129_ (
    .A(_073_),
    .B(_086_),
    .X(_087_)
  );
  sky130_fd_sc_hd__nand3_2 _130_ (
    .A(_071_),
    .B(_072_),
    .C(_087_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__or2_2 _131_ (
    .A(_085_),
    .B(_088_),
    .X(_089_)
  );
  sky130_fd_sc_hd__a21oi_2 _132_ (
    .A1(_083_),
    .A2(_084_),
    .B1(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__or2b_2 _133_ (
    .A(\rg_cfloat152[6] ),
    .B_N(\rg_bias[4] ),
    .X(_091_)
  );
  sky130_fd_sc_hd__a31oi_2 _134_ (
    .A1(_070_),
    .A2(_079_),
    .A3(_091_),
    .B1(_081_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__or2_2 _135_ (
    .A(\rg_bias[5] ),
    .B(_092_),
    .X(_093_)
  );
  sky130_fd_sc_hd__nor2_2 _136_ (
    .A(_090_),
    .B(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__and3_2 _137_ (
    .A(RST_N),
    .B(_068_),
    .C(_094_),
    .X(_095_)
  );
  sky130_fd_sc_hd__buf_1 _138_ (
    .A(_095_),
    .X(_002_)
  );
  sky130_fd_sc_hd__o211a_2 _139_ (
    .A1(\fp32_mantissa__h323[21] ),
    .A2(_068_),
    .B1(RST_N),
    .C1(\fp32_mantissa__h323[22] ),
    .X(_003_)
  );
  sky130_fd_sc_hd__o31a_2 _140_ (
    .A1(\fp32_mantissa__h323[22] ),
    .A2(\fp32_mantissa__h323[21] ),
    .A3(_068_),
    .B1(RST_N),
    .X(_096_)
  );
  sky130_fd_sc_hd__inv_2 _141_ (
    .A(_068_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2_2 _142_ (
    .A(\fp32_mantissa__h323[22] ),
    .B(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__xnor2_2 _143_ (
    .A(_087_),
    .B(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__and2_2 _144_ (
    .A(_096_),
    .B(_099_),
    .X(_100_)
  );
  sky130_fd_sc_hd__buf_1 _145_ (
    .A(_100_),
    .X(_004_)
  );
  sky130_fd_sc_hd__o21a_2 _146_ (
    .A1(\fp32_mantissa__h323[22] ),
    .A2(\fp32_mantissa__h323[21] ),
    .B1(_097_),
    .X(_101_)
  );
  sky130_fd_sc_hd__xnor2_2 _147_ (
    .A(_072_),
    .B(_086_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__o21ai_2 _148_ (
    .A1(\fp32_mantissa__h323[22] ),
    .A2(\fp32_mantissa__h323[21] ),
    .B1(_097_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__buf_1 _149_ (
    .A(_103_),
    .X(_104_)
  );
  sky130_fd_sc_hd__and2b_2 _150_ (
    .A_N(\fp32_mantissa__h323[22] ),
    .B(\fp32_mantissa__h323[21] ),
    .X(_105_)
  );
  sky130_fd_sc_hd__o21a_2 _151_ (
    .A1(\rg_bias[0] ),
    .A2(_105_),
    .B1(\rg_bias[1] ),
    .X(_025_)
  );
  sky130_fd_sc_hd__or3_2 _152_ (
    .A(\rg_bias[0] ),
    .B(\rg_bias[1] ),
    .C(_105_),
    .X(_026_)
  );
  sky130_fd_sc_hd__or3b_2 _153_ (
    .A(_104_),
    .B(_025_),
    .C_N(_026_),
    .X(_027_)
  );
  sky130_fd_sc_hd__buf_1 _154_ (
    .A(_096_),
    .X(_028_)
  );
  sky130_fd_sc_hd__o211a_2 _155_ (
    .A1(_101_),
    .A2(_102_),
    .B1(_027_),
    .C1(_028_),
    .X(_005_)
  );
  sky130_fd_sc_hd__nand2_2 _156_ (
    .A(_072_),
    .B(_087_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2_2 _157_ (
    .A(_071_),
    .B(_075_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__or2_2 _158_ (
    .A(_071_),
    .B(_075_),
    .X(_031_)
  );
  sky130_fd_sc_hd__and3_2 _159_ (
    .A(_029_),
    .B(_030_),
    .C(_031_),
    .X(_032_)
  );
  sky130_fd_sc_hd__nand2_2 _160_ (
    .A(_088_),
    .B(_104_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__and2_2 _161_ (
    .A(\rg_bias[2] ),
    .B(_025_),
    .X(_034_)
  );
  sky130_fd_sc_hd__nor2_2 _162_ (
    .A(\rg_bias[2] ),
    .B(_025_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__or3_2 _163_ (
    .A(_103_),
    .B(_034_),
    .C(_035_),
    .X(_036_)
  );
  sky130_fd_sc_hd__o211a_2 _164_ (
    .A1(_032_),
    .A2(_033_),
    .B1(_036_),
    .C1(_028_),
    .X(_006_)
  );
  sky130_fd_sc_hd__and3_2 _165_ (
    .A(\rg_bias[2] ),
    .B(\rg_bias[3] ),
    .C(_025_),
    .X(_037_)
  );
  sky130_fd_sc_hd__nor2_2 _166_ (
    .A(\rg_bias[3] ),
    .B(_034_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__xor2_2 _167_ (
    .A(_085_),
    .B(_088_),
    .X(_039_)
  );
  sky130_fd_sc_hd__nand2_2 _168_ (
    .A(_077_),
    .B(_030_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__mux2_2 _169_ (
    .A0(_085_),
    .A1(_039_),
    .S(_040_),
    .X(_041_)
  );
  sky130_fd_sc_hd__nand2_2 _170_ (
    .A(_104_),
    .B(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o311a_2 _171_ (
    .A1(_104_),
    .A2(_037_),
    .A3(_038_),
    .B1(_042_),
    .C1(_028_),
    .X(_007_)
  );
  sky130_fd_sc_hd__nor2_2 _172_ (
    .A(\rg_bias[4] ),
    .B(_037_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__and3_2 _173_ (
    .A(\rg_bias[3] ),
    .B(\rg_bias[4] ),
    .C(_034_),
    .X(_044_)
  );
  sky130_fd_sc_hd__a311o_2 _174_ (
    .A1(_089_),
    .A2(_083_),
    .A3(_084_),
    .B1(_090_),
    .C1(_101_),
    .X(_045_)
  );
  sky130_fd_sc_hd__o311a_2 _175_ (
    .A1(_104_),
    .A2(_043_),
    .A3(_044_),
    .B1(_045_),
    .C1(_028_),
    .X(_008_)
  );
  sky130_fd_sc_hd__xnor2_2 _176_ (
    .A(\rg_bias[5] ),
    .B(_092_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor2_2 _177_ (
    .A(_090_),
    .B(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a21o_2 _178_ (
    .A1(_090_),
    .A2(_046_),
    .B1(_101_),
    .X(_048_)
  );
  sky130_fd_sc_hd__nand2_2 _179_ (
    .A(\rg_bias[5] ),
    .B(_044_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__o21a_2 _180_ (
    .A1(\rg_bias[5] ),
    .A2(_044_),
    .B1(_101_),
    .X(_050_)
  );
  sky130_fd_sc_hd__nand2_2 _181_ (
    .A(_049_),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__o211a_2 _182_ (
    .A1(_047_),
    .A2(_048_),
    .B1(_051_),
    .C1(_028_),
    .X(_009_)
  );
  sky130_fd_sc_hd__o221a_2 _183_ (
    .A1(_090_),
    .A2(_093_),
    .B1(_104_),
    .B2(_049_),
    .C1(_028_),
    .X(_010_)
  );
  sky130_fd_sc_hd__and2_2 _184_ (
    .A(RST_N),
    .B(bias_in_bias[0]),
    .X(_052_)
  );
  sky130_fd_sc_hd__buf_1 _185_ (
    .A(_052_),
    .X(_011_)
  );
  sky130_fd_sc_hd__and2_2 _186_ (
    .A(RST_N),
    .B(bias_in_bias[1]),
    .X(_053_)
  );
  sky130_fd_sc_hd__buf_1 _187_ (
    .A(_053_),
    .X(_012_)
  );
  sky130_fd_sc_hd__and2_2 _188_ (
    .A(RST_N),
    .B(bias_in_bias[2]),
    .X(_054_)
  );
  sky130_fd_sc_hd__buf_1 _189_ (
    .A(_054_),
    .X(_013_)
  );
  sky130_fd_sc_hd__and2_2 _190_ (
    .A(RST_N),
    .B(bias_in_bias[3]),
    .X(_055_)
  );
  sky130_fd_sc_hd__buf_1 _191_ (
    .A(_055_),
    .X(_014_)
  );
  sky130_fd_sc_hd__and2_2 _192_ (
    .A(RST_N),
    .B(bias_in_bias[4]),
    .X(_056_)
  );
  sky130_fd_sc_hd__buf_1 _193_ (
    .A(_056_),
    .X(_015_)
  );
  sky130_fd_sc_hd__and2_2 _194_ (
    .A(RST_N),
    .B(bias_in_bias[5]),
    .X(_057_)
  );
  sky130_fd_sc_hd__buf_1 _195_ (
    .A(_057_),
    .X(_016_)
  );
  sky130_fd_sc_hd__and2_2 _196_ (
    .A(RST_N),
    .B(cfloat152_in_cfloat_in[0]),
    .X(_058_)
  );
  sky130_fd_sc_hd__buf_1 _197_ (
    .A(_058_),
    .X(_017_)
  );
  sky130_fd_sc_hd__and2_2 _198_ (
    .A(RST_N),
    .B(cfloat152_in_cfloat_in[1]),
    .X(_059_)
  );
  sky130_fd_sc_hd__buf_1 _199_ (
    .A(_059_),
    .X(_018_)
  );
  sky130_fd_sc_hd__and2_2 _200_ (
    .A(RST_N),
    .B(cfloat152_in_cfloat_in[2]),
    .X(_060_)
  );
  sky130_fd_sc_hd__buf_1 _201_ (
    .A(_060_),
    .X(_019_)
  );
  sky130_fd_sc_hd__and2_2 _202_ (
    .A(RST_N),
    .B(cfloat152_in_cfloat_in[3]),
    .X(_061_)
  );
  sky130_fd_sc_hd__buf_1 _203_ (
    .A(_061_),
    .X(_020_)
  );
  sky130_fd_sc_hd__and2_2 _204_ (
    .A(RST_N),
    .B(cfloat152_in_cfloat_in[4]),
    .X(_062_)
  );
  sky130_fd_sc_hd__buf_1 _205_ (
    .A(_062_),
    .X(_021_)
  );
  sky130_fd_sc_hd__and2_2 _206_ (
    .A(RST_N),
    .B(cfloat152_in_cfloat_in[5]),
    .X(_063_)
  );
  sky130_fd_sc_hd__buf_1 _207_ (
    .A(_063_),
    .X(_022_)
  );
  sky130_fd_sc_hd__and2_2 _208_ (
    .A(RST_N),
    .B(cfloat152_in_cfloat_in[6]),
    .X(_064_)
  );
  sky130_fd_sc_hd__buf_1 _209_ (
    .A(_064_),
    .X(_023_)
  );
  sky130_fd_sc_hd__and2_2 _210_ (
    .A(RST_N),
    .B(cfloat152_in_cfloat_in[7]),
    .X(_065_)
  );
  sky130_fd_sc_hd__buf_1 _211_ (
    .A(_065_),
    .X(_024_)
  );
  sky130_fd_sc_hd__dfxtp_2 _212_ (
    .CLK(CLK),
    .D(_000_),
    .Q(fp32_out[31])
  );
  sky130_fd_sc_hd__dfxtp_2 _213_ (
    .CLK(CLK),
    .D(_001_),
    .Q(fp32_out[21])
  );
  sky130_fd_sc_hd__dfxtp_2 _214_ (
    .CLK(CLK),
    .D(_002_),
    .Q(fp32_out[30])
  );
  sky130_fd_sc_hd__dfxtp_2 _215_ (
    .CLK(CLK),
    .D(_003_),
    .Q(fp32_out[22])
  );
  sky130_fd_sc_hd__dfxtp_2 _216_ (
    .CLK(CLK),
    .D(_004_),
    .Q(fp32_out[23])
  );
  sky130_fd_sc_hd__dfxtp_2 _217_ (
    .CLK(CLK),
    .D(_005_),
    .Q(fp32_out[24])
  );
  sky130_fd_sc_hd__dfxtp_2 _218_ (
    .CLK(CLK),
    .D(_006_),
    .Q(fp32_out[25])
  );
  sky130_fd_sc_hd__dfxtp_2 _219_ (
    .CLK(CLK),
    .D(_007_),
    .Q(fp32_out[26])
  );
  sky130_fd_sc_hd__dfxtp_2 _220_ (
    .CLK(CLK),
    .D(_008_),
    .Q(fp32_out[27])
  );
  sky130_fd_sc_hd__dfxtp_2 _221_ (
    .CLK(CLK),
    .D(_009_),
    .Q(fp32_out[28])
  );
  sky130_fd_sc_hd__dfxtp_2 _222_ (
    .CLK(CLK),
    .D(_010_),
    .Q(fp32_out[29])
  );
  sky130_fd_sc_hd__dfxtp_2 _223_ (
    .CLK(CLK),
    .D(_011_),
    .Q(\rg_bias[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _224_ (
    .CLK(CLK),
    .D(_012_),
    .Q(\rg_bias[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _225_ (
    .CLK(CLK),
    .D(_013_),
    .Q(\rg_bias[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _226_ (
    .CLK(CLK),
    .D(_014_),
    .Q(\rg_bias[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _227_ (
    .CLK(CLK),
    .D(_015_),
    .Q(\rg_bias[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _228_ (
    .CLK(CLK),
    .D(_016_),
    .Q(\rg_bias[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _229_ (
    .CLK(CLK),
    .D(_017_),
    .Q(\fp32_mantissa__h323[21] )
  );
  sky130_fd_sc_hd__dfxtp_2 _230_ (
    .CLK(CLK),
    .D(_018_),
    .Q(\fp32_mantissa__h323[22] )
  );
  sky130_fd_sc_hd__dfxtp_2 _231_ (
    .CLK(CLK),
    .D(_019_),
    .Q(\rg_cfloat152[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _232_ (
    .CLK(CLK),
    .D(_020_),
    .Q(\rg_cfloat152[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _233_ (
    .CLK(CLK),
    .D(_021_),
    .Q(\rg_cfloat152[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _234_ (
    .CLK(CLK),
    .D(_022_),
    .Q(\rg_cfloat152[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _235_ (
    .CLK(CLK),
    .D(_023_),
    .Q(\rg_cfloat152[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _236_ (
    .CLK(CLK),
    .D(_024_),
    .Q(\rg_cfloat152[7] )
  );
  sky130_fd_sc_hd__buf_2 _237_ (
    .A(1'b0),
    .X(fp32_out[0])
  );
  sky130_fd_sc_hd__buf_2 _238_ (
    .A(1'b0),
    .X(fp32_out[1])
  );
  sky130_fd_sc_hd__buf_2 _239_ (
    .A(1'b0),
    .X(fp32_out[2])
  );
  sky130_fd_sc_hd__buf_2 _240_ (
    .A(1'b0),
    .X(fp32_out[3])
  );
  sky130_fd_sc_hd__buf_2 _241_ (
    .A(1'b0),
    .X(fp32_out[4])
  );
  sky130_fd_sc_hd__buf_2 _242_ (
    .A(1'b0),
    .X(fp32_out[5])
  );
  sky130_fd_sc_hd__buf_2 _243_ (
    .A(1'b0),
    .X(fp32_out[6])
  );
  sky130_fd_sc_hd__buf_2 _244_ (
    .A(1'b0),
    .X(fp32_out[7])
  );
  sky130_fd_sc_hd__buf_2 _245_ (
    .A(1'b0),
    .X(fp32_out[8])
  );
  sky130_fd_sc_hd__buf_2 _246_ (
    .A(1'b0),
    .X(fp32_out[9])
  );
  sky130_fd_sc_hd__buf_2 _247_ (
    .A(1'b0),
    .X(fp32_out[10])
  );
  sky130_fd_sc_hd__buf_2 _248_ (
    .A(1'b0),
    .X(fp32_out[11])
  );
  sky130_fd_sc_hd__buf_2 _249_ (
    .A(1'b0),
    .X(fp32_out[12])
  );
  sky130_fd_sc_hd__buf_2 _250_ (
    .A(1'b0),
    .X(fp32_out[13])
  );
  sky130_fd_sc_hd__buf_2 _251_ (
    .A(1'b0),
    .X(fp32_out[14])
  );
  sky130_fd_sc_hd__buf_2 _252_ (
    .A(1'b0),
    .X(fp32_out[15])
  );
  sky130_fd_sc_hd__buf_2 _253_ (
    .A(1'b0),
    .X(fp32_out[16])
  );
  sky130_fd_sc_hd__buf_2 _254_ (
    .A(1'b0),
    .X(fp32_out[17])
  );
  sky130_fd_sc_hd__buf_2 _255_ (
    .A(1'b0),
    .X(fp32_out[18])
  );
  sky130_fd_sc_hd__buf_2 _256_ (
    .A(1'b0),
    .X(fp32_out[19])
  );
  sky130_fd_sc_hd__buf_2 _257_ (
    .A(1'b0),
    .X(fp32_out[20])
  );
endmodule
