/* Generated by Yosys 0.33 (git sha1 2584903a060, clang++ 11.1.0 -fPIC -Os) */

module mk_bfloat16_fp32(CLK, RST_N, bfloat16_in_bfloat_in, fp32_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  input CLK;
  wire CLK;
  input RST_N;
  wire RST_N;
  wire \_theResult___snd_mantissa__h475[16] ;
  wire \_theResult___snd_mantissa__h475[17] ;
  wire \_theResult___snd_mantissa__h475[18] ;
  wire \_theResult___snd_mantissa__h475[19] ;
  wire \_theResult___snd_mantissa__h475[20] ;
  wire \_theResult___snd_mantissa__h475[21] ;
  wire \_theResult___snd_mantissa__h475[22] ;
  input [15:0] bfloat16_in_bfloat_in;
  wire [15:0] bfloat16_in_bfloat_in;
  output [31:0] fp32_out;
  wire [31:0] fp32_out;
  wire \rg_bfloat16[10] ;
  wire \rg_bfloat16[11] ;
  wire \rg_bfloat16[12] ;
  wire \rg_bfloat16[13] ;
  wire \rg_bfloat16[14] ;
  wire \rg_bfloat16[15] ;
  wire \rg_bfloat16[7] ;
  wire \rg_bfloat16[8] ;
  wire \rg_bfloat16[9] ;
  sky130_fd_sc_hd__nand4_2 _065_ (
    .A(\rg_bfloat16[12] ),
    .B(\rg_bfloat16[11] ),
    .C(\rg_bfloat16[14] ),
    .D(\rg_bfloat16[13] ),
    .Y(_049_)
  );
  sky130_fd_sc_hd__buf_1 _066_ (
    .A(_049_),
    .X(_050_)
  );
  sky130_fd_sc_hd__nand4_2 _067_ (
    .A(\rg_bfloat16[8] ),
    .B(\rg_bfloat16[7] ),
    .C(\rg_bfloat16[10] ),
    .D(\rg_bfloat16[9] ),
    .Y(_051_)
  );
  sky130_fd_sc_hd__buf_1 _068_ (
    .A(_051_),
    .X(_052_)
  );
  sky130_fd_sc_hd__o211a_2 _069_ (
    .A1(_050_),
    .A2(_052_),
    .B1(\_theResult___snd_mantissa__h475[16] ),
    .C1(RST_N),
    .X(_000_)
  );
  sky130_fd_sc_hd__inv_2 _070_ (
    .A(\_theResult___snd_mantissa__h475[16] ),
    .Y(_053_)
  );
  sky130_fd_sc_hd__o311a_2 _071_ (
    .A1(_053_),
    .A2(_050_),
    .A3(_052_),
    .B1(RST_N),
    .C1(\_theResult___snd_mantissa__h475[17] ),
    .X(_001_)
  );
  sky130_fd_sc_hd__o311a_2 _072_ (
    .A1(_053_),
    .A2(_050_),
    .A3(_052_),
    .B1(\_theResult___snd_mantissa__h475[18] ),
    .C1(RST_N),
    .X(_002_)
  );
  sky130_fd_sc_hd__o311a_2 _073_ (
    .A1(_053_),
    .A2(_050_),
    .A3(_052_),
    .B1(\_theResult___snd_mantissa__h475[19] ),
    .C1(RST_N),
    .X(_003_)
  );
  sky130_fd_sc_hd__o311a_2 _074_ (
    .A1(_053_),
    .A2(_050_),
    .A3(_052_),
    .B1(\_theResult___snd_mantissa__h475[20] ),
    .C1(RST_N),
    .X(_004_)
  );
  sky130_fd_sc_hd__o311a_2 _075_ (
    .A1(_053_),
    .A2(_050_),
    .A3(_052_),
    .B1(\_theResult___snd_mantissa__h475[21] ),
    .C1(RST_N),
    .X(_005_)
  );
  sky130_fd_sc_hd__and2_2 _076_ (
    .A(\_theResult___snd_mantissa__h475[22] ),
    .B(RST_N),
    .X(_054_)
  );
  sky130_fd_sc_hd__buf_1 _077_ (
    .A(_054_),
    .X(_006_)
  );
  sky130_fd_sc_hd__and2_2 _078_ (
    .A(\rg_bfloat16[7] ),
    .B(RST_N),
    .X(_055_)
  );
  sky130_fd_sc_hd__buf_1 _079_ (
    .A(_055_),
    .X(_007_)
  );
  sky130_fd_sc_hd__and2_2 _080_ (
    .A(\rg_bfloat16[8] ),
    .B(RST_N),
    .X(_056_)
  );
  sky130_fd_sc_hd__buf_1 _081_ (
    .A(_056_),
    .X(_008_)
  );
  sky130_fd_sc_hd__and2_2 _082_ (
    .A(\rg_bfloat16[9] ),
    .B(RST_N),
    .X(_057_)
  );
  sky130_fd_sc_hd__buf_1 _083_ (
    .A(_057_),
    .X(_009_)
  );
  sky130_fd_sc_hd__and2_2 _084_ (
    .A(\rg_bfloat16[10] ),
    .B(RST_N),
    .X(_058_)
  );
  sky130_fd_sc_hd__buf_1 _085_ (
    .A(_058_),
    .X(_010_)
  );
  sky130_fd_sc_hd__and2_2 _086_ (
    .A(\rg_bfloat16[11] ),
    .B(RST_N),
    .X(_059_)
  );
  sky130_fd_sc_hd__buf_1 _087_ (
    .A(_059_),
    .X(_011_)
  );
  sky130_fd_sc_hd__and2_2 _088_ (
    .A(\rg_bfloat16[12] ),
    .B(RST_N),
    .X(_060_)
  );
  sky130_fd_sc_hd__buf_1 _089_ (
    .A(_060_),
    .X(_012_)
  );
  sky130_fd_sc_hd__and2_2 _090_ (
    .A(\rg_bfloat16[13] ),
    .B(RST_N),
    .X(_061_)
  );
  sky130_fd_sc_hd__buf_1 _091_ (
    .A(_061_),
    .X(_013_)
  );
  sky130_fd_sc_hd__and2_2 _092_ (
    .A(\rg_bfloat16[14] ),
    .B(RST_N),
    .X(_062_)
  );
  sky130_fd_sc_hd__buf_1 _093_ (
    .A(_062_),
    .X(_014_)
  );
  sky130_fd_sc_hd__and2_2 _094_ (
    .A(RST_N),
    .B(\rg_bfloat16[15] ),
    .X(_063_)
  );
  sky130_fd_sc_hd__buf_1 _095_ (
    .A(_063_),
    .X(_015_)
  );
  sky130_fd_sc_hd__inv_2 _096_ (
    .A(RST_N),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor4_2 _097_ (
    .A(_053_),
    .B(_064_),
    .C(_049_),
    .D(_051_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__and2_2 _098_ (
    .A(RST_N),
    .B(bfloat16_in_bfloat_in[0]),
    .X(_033_)
  );
  sky130_fd_sc_hd__buf_1 _099_ (
    .A(_033_),
    .X(_017_)
  );
  sky130_fd_sc_hd__and2_2 _100_ (
    .A(RST_N),
    .B(bfloat16_in_bfloat_in[1]),
    .X(_034_)
  );
  sky130_fd_sc_hd__buf_1 _101_ (
    .A(_034_),
    .X(_018_)
  );
  sky130_fd_sc_hd__and2_2 _102_ (
    .A(RST_N),
    .B(bfloat16_in_bfloat_in[2]),
    .X(_035_)
  );
  sky130_fd_sc_hd__buf_1 _103_ (
    .A(_035_),
    .X(_019_)
  );
  sky130_fd_sc_hd__and2_2 _104_ (
    .A(RST_N),
    .B(bfloat16_in_bfloat_in[3]),
    .X(_036_)
  );
  sky130_fd_sc_hd__buf_1 _105_ (
    .A(_036_),
    .X(_020_)
  );
  sky130_fd_sc_hd__and2_2 _106_ (
    .A(RST_N),
    .B(bfloat16_in_bfloat_in[4]),
    .X(_037_)
  );
  sky130_fd_sc_hd__buf_1 _107_ (
    .A(_037_),
    .X(_021_)
  );
  sky130_fd_sc_hd__and2_2 _108_ (
    .A(RST_N),
    .B(bfloat16_in_bfloat_in[5]),
    .X(_038_)
  );
  sky130_fd_sc_hd__buf_1 _109_ (
    .A(_038_),
    .X(_022_)
  );
  sky130_fd_sc_hd__and2_2 _110_ (
    .A(RST_N),
    .B(bfloat16_in_bfloat_in[6]),
    .X(_039_)
  );
  sky130_fd_sc_hd__buf_1 _111_ (
    .A(_039_),
    .X(_023_)
  );
  sky130_fd_sc_hd__and2_2 _112_ (
    .A(RST_N),
    .B(bfloat16_in_bfloat_in[7]),
    .X(_040_)
  );
  sky130_fd_sc_hd__buf_1 _113_ (
    .A(_040_),
    .X(_024_)
  );
  sky130_fd_sc_hd__and2_2 _114_ (
    .A(RST_N),
    .B(bfloat16_in_bfloat_in[8]),
    .X(_041_)
  );
  sky130_fd_sc_hd__buf_1 _115_ (
    .A(_041_),
    .X(_025_)
  );
  sky130_fd_sc_hd__and2_2 _116_ (
    .A(RST_N),
    .B(bfloat16_in_bfloat_in[9]),
    .X(_042_)
  );
  sky130_fd_sc_hd__buf_1 _117_ (
    .A(_042_),
    .X(_026_)
  );
  sky130_fd_sc_hd__and2_2 _118_ (
    .A(RST_N),
    .B(bfloat16_in_bfloat_in[10]),
    .X(_043_)
  );
  sky130_fd_sc_hd__buf_1 _119_ (
    .A(_043_),
    .X(_027_)
  );
  sky130_fd_sc_hd__and2_2 _120_ (
    .A(RST_N),
    .B(bfloat16_in_bfloat_in[11]),
    .X(_044_)
  );
  sky130_fd_sc_hd__buf_1 _121_ (
    .A(_044_),
    .X(_028_)
  );
  sky130_fd_sc_hd__and2_2 _122_ (
    .A(RST_N),
    .B(bfloat16_in_bfloat_in[12]),
    .X(_045_)
  );
  sky130_fd_sc_hd__buf_1 _123_ (
    .A(_045_),
    .X(_029_)
  );
  sky130_fd_sc_hd__and2_2 _124_ (
    .A(RST_N),
    .B(bfloat16_in_bfloat_in[13]),
    .X(_046_)
  );
  sky130_fd_sc_hd__buf_1 _125_ (
    .A(_046_),
    .X(_030_)
  );
  sky130_fd_sc_hd__and2_2 _126_ (
    .A(RST_N),
    .B(bfloat16_in_bfloat_in[14]),
    .X(_047_)
  );
  sky130_fd_sc_hd__buf_1 _127_ (
    .A(_047_),
    .X(_031_)
  );
  sky130_fd_sc_hd__and2_2 _128_ (
    .A(RST_N),
    .B(bfloat16_in_bfloat_in[15]),
    .X(_048_)
  );
  sky130_fd_sc_hd__buf_1 _129_ (
    .A(_048_),
    .X(_032_)
  );
  sky130_fd_sc_hd__dfxtp_2 _130_ (
    .CLK(CLK),
    .D(_000_),
    .Q(fp32_out[16])
  );
  sky130_fd_sc_hd__dfxtp_2 _131_ (
    .CLK(CLK),
    .D(_001_),
    .Q(fp32_out[17])
  );
  sky130_fd_sc_hd__dfxtp_2 _132_ (
    .CLK(CLK),
    .D(_002_),
    .Q(fp32_out[18])
  );
  sky130_fd_sc_hd__dfxtp_2 _133_ (
    .CLK(CLK),
    .D(_003_),
    .Q(fp32_out[19])
  );
  sky130_fd_sc_hd__dfxtp_2 _134_ (
    .CLK(CLK),
    .D(_004_),
    .Q(fp32_out[20])
  );
  sky130_fd_sc_hd__dfxtp_2 _135_ (
    .CLK(CLK),
    .D(_005_),
    .Q(fp32_out[21])
  );
  sky130_fd_sc_hd__dfxtp_2 _136_ (
    .CLK(CLK),
    .D(_006_),
    .Q(fp32_out[22])
  );
  sky130_fd_sc_hd__dfxtp_2 _137_ (
    .CLK(CLK),
    .D(_007_),
    .Q(fp32_out[23])
  );
  sky130_fd_sc_hd__dfxtp_2 _138_ (
    .CLK(CLK),
    .D(_008_),
    .Q(fp32_out[24])
  );
  sky130_fd_sc_hd__dfxtp_2 _139_ (
    .CLK(CLK),
    .D(_009_),
    .Q(fp32_out[25])
  );
  sky130_fd_sc_hd__dfxtp_2 _140_ (
    .CLK(CLK),
    .D(_010_),
    .Q(fp32_out[26])
  );
  sky130_fd_sc_hd__dfxtp_2 _141_ (
    .CLK(CLK),
    .D(_011_),
    .Q(fp32_out[27])
  );
  sky130_fd_sc_hd__dfxtp_2 _142_ (
    .CLK(CLK),
    .D(_012_),
    .Q(fp32_out[28])
  );
  sky130_fd_sc_hd__dfxtp_2 _143_ (
    .CLK(CLK),
    .D(_013_),
    .Q(fp32_out[29])
  );
  sky130_fd_sc_hd__dfxtp_2 _144_ (
    .CLK(CLK),
    .D(_014_),
    .Q(fp32_out[30])
  );
  sky130_fd_sc_hd__dfxtp_2 _145_ (
    .CLK(CLK),
    .D(_015_),
    .Q(fp32_out[31])
  );
  sky130_fd_sc_hd__dfxtp_2 _146_ (
    .CLK(CLK),
    .D(_016_),
    .Q(fp32_out[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _147_ (
    .CLK(CLK),
    .D(_017_),
    .Q(\_theResult___snd_mantissa__h475[16] )
  );
  sky130_fd_sc_hd__dfxtp_2 _148_ (
    .CLK(CLK),
    .D(_018_),
    .Q(\_theResult___snd_mantissa__h475[17] )
  );
  sky130_fd_sc_hd__dfxtp_2 _149_ (
    .CLK(CLK),
    .D(_019_),
    .Q(\_theResult___snd_mantissa__h475[18] )
  );
  sky130_fd_sc_hd__dfxtp_2 _150_ (
    .CLK(CLK),
    .D(_020_),
    .Q(\_theResult___snd_mantissa__h475[19] )
  );
  sky130_fd_sc_hd__dfxtp_2 _151_ (
    .CLK(CLK),
    .D(_021_),
    .Q(\_theResult___snd_mantissa__h475[20] )
  );
  sky130_fd_sc_hd__dfxtp_2 _152_ (
    .CLK(CLK),
    .D(_022_),
    .Q(\_theResult___snd_mantissa__h475[21] )
  );
  sky130_fd_sc_hd__dfxtp_2 _153_ (
    .CLK(CLK),
    .D(_023_),
    .Q(\_theResult___snd_mantissa__h475[22] )
  );
  sky130_fd_sc_hd__dfxtp_2 _154_ (
    .CLK(CLK),
    .D(_024_),
    .Q(\rg_bfloat16[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _155_ (
    .CLK(CLK),
    .D(_025_),
    .Q(\rg_bfloat16[8] )
  );
  sky130_fd_sc_hd__dfxtp_2 _156_ (
    .CLK(CLK),
    .D(_026_),
    .Q(\rg_bfloat16[9] )
  );
  sky130_fd_sc_hd__dfxtp_2 _157_ (
    .CLK(CLK),
    .D(_027_),
    .Q(\rg_bfloat16[10] )
  );
  sky130_fd_sc_hd__dfxtp_2 _158_ (
    .CLK(CLK),
    .D(_028_),
    .Q(\rg_bfloat16[11] )
  );
  sky130_fd_sc_hd__dfxtp_2 _159_ (
    .CLK(CLK),
    .D(_029_),
    .Q(\rg_bfloat16[12] )
  );
  sky130_fd_sc_hd__dfxtp_2 _160_ (
    .CLK(CLK),
    .D(_030_),
    .Q(\rg_bfloat16[13] )
  );
  sky130_fd_sc_hd__dfxtp_2 _161_ (
    .CLK(CLK),
    .D(_031_),
    .Q(\rg_bfloat16[14] )
  );
  sky130_fd_sc_hd__dfxtp_2 _162_ (
    .CLK(CLK),
    .D(_032_),
    .Q(\rg_bfloat16[15] )
  );
  sky130_fd_sc_hd__buf_2 _163_ (
    .A(1'b0),
    .X(fp32_out[1])
  );
  sky130_fd_sc_hd__buf_2 _164_ (
    .A(1'b0),
    .X(fp32_out[2])
  );
  sky130_fd_sc_hd__buf_2 _165_ (
    .A(1'b0),
    .X(fp32_out[3])
  );
  sky130_fd_sc_hd__buf_2 _166_ (
    .A(1'b0),
    .X(fp32_out[4])
  );
  sky130_fd_sc_hd__buf_2 _167_ (
    .A(1'b0),
    .X(fp32_out[5])
  );
  sky130_fd_sc_hd__buf_2 _168_ (
    .A(1'b0),
    .X(fp32_out[6])
  );
  sky130_fd_sc_hd__buf_2 _169_ (
    .A(1'b0),
    .X(fp32_out[7])
  );
  sky130_fd_sc_hd__buf_2 _170_ (
    .A(1'b0),
    .X(fp32_out[8])
  );
  sky130_fd_sc_hd__buf_2 _171_ (
    .A(1'b0),
    .X(fp32_out[9])
  );
  sky130_fd_sc_hd__buf_2 _172_ (
    .A(1'b0),
    .X(fp32_out[10])
  );
  sky130_fd_sc_hd__buf_2 _173_ (
    .A(1'b0),
    .X(fp32_out[11])
  );
  sky130_fd_sc_hd__buf_2 _174_ (
    .A(1'b0),
    .X(fp32_out[12])
  );
  sky130_fd_sc_hd__buf_2 _175_ (
    .A(1'b0),
    .X(fp32_out[13])
  );
  sky130_fd_sc_hd__buf_2 _176_ (
    .A(1'b0),
    .X(fp32_out[14])
  );
  sky130_fd_sc_hd__buf_2 _177_ (
    .A(1'b0),
    .X(fp32_out[15])
  );
endmodule
