/* Generated by Yosys 0.33 (git sha1 2584903a060, clang++ 11.1.0 -fPIC -Os) */

module mk_fp32_cfloat152(CLK, RST_N, fp32_in_fp_in, bias_in_bias, cfloat152_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  input CLK;
  wire CLK;
  input RST_N;
  wire RST_N;
  wire \_128_MINUS_0_CONCAT_rg_bias_0_MINUS_4___d11[0] ;
  input [5:0] bias_in_bias;
  wire [5:0] bias_in_bias;
  output [7:0] cfloat152_out;
  wire [7:0] cfloat152_out;
  input [31:0] fp32_in_fp_in;
  wire [31:0] fp32_in_fp_in;
  wire \rg_bias[1] ;
  wire \rg_bias[2] ;
  wire \rg_bias[3] ;
  wire \rg_bias[4] ;
  wire \rg_bias[5] ;
  wire \rg_cfloat152$D_IN[7] ;
  wire \rg_fp32[20] ;
  wire \rg_fp32[21] ;
  wire \rg_fp32[22] ;
  wire \rg_fp32[23] ;
  wire \rg_fp32[24] ;
  wire \rg_fp32[25] ;
  wire \rg_fp32[26] ;
  wire \rg_fp32[27] ;
  wire \rg_fp32[28] ;
  wire \rg_fp32[29] ;
  wire \rg_fp32[30] ;
  sky130_fd_sc_hd__and2_2 _184_ (
    .A(RST_N),
    .B(fp32_in_fp_in[20]),
    .X(_026_)
  );
  sky130_fd_sc_hd__buf_1 _185_ (
    .A(_026_),
    .X(_000_)
  );
  sky130_fd_sc_hd__and2_2 _186_ (
    .A(RST_N),
    .B(fp32_in_fp_in[21]),
    .X(_027_)
  );
  sky130_fd_sc_hd__buf_1 _187_ (
    .A(_027_),
    .X(_001_)
  );
  sky130_fd_sc_hd__and2_2 _188_ (
    .A(RST_N),
    .B(fp32_in_fp_in[22]),
    .X(_028_)
  );
  sky130_fd_sc_hd__buf_1 _189_ (
    .A(_028_),
    .X(_002_)
  );
  sky130_fd_sc_hd__and2_2 _190_ (
    .A(RST_N),
    .B(fp32_in_fp_in[23]),
    .X(_029_)
  );
  sky130_fd_sc_hd__buf_1 _191_ (
    .A(_029_),
    .X(_003_)
  );
  sky130_fd_sc_hd__and2_2 _192_ (
    .A(RST_N),
    .B(fp32_in_fp_in[24]),
    .X(_030_)
  );
  sky130_fd_sc_hd__buf_1 _193_ (
    .A(_030_),
    .X(_004_)
  );
  sky130_fd_sc_hd__and2_2 _194_ (
    .A(RST_N),
    .B(fp32_in_fp_in[25]),
    .X(_031_)
  );
  sky130_fd_sc_hd__buf_1 _195_ (
    .A(_031_),
    .X(_005_)
  );
  sky130_fd_sc_hd__and2_2 _196_ (
    .A(RST_N),
    .B(fp32_in_fp_in[26]),
    .X(_032_)
  );
  sky130_fd_sc_hd__buf_1 _197_ (
    .A(_032_),
    .X(_006_)
  );
  sky130_fd_sc_hd__and2_2 _198_ (
    .A(RST_N),
    .B(fp32_in_fp_in[27]),
    .X(_033_)
  );
  sky130_fd_sc_hd__buf_1 _199_ (
    .A(_033_),
    .X(_007_)
  );
  sky130_fd_sc_hd__and2_2 _200_ (
    .A(RST_N),
    .B(fp32_in_fp_in[28]),
    .X(_034_)
  );
  sky130_fd_sc_hd__buf_1 _201_ (
    .A(_034_),
    .X(_008_)
  );
  sky130_fd_sc_hd__and2_2 _202_ (
    .A(RST_N),
    .B(fp32_in_fp_in[29]),
    .X(_035_)
  );
  sky130_fd_sc_hd__buf_1 _203_ (
    .A(_035_),
    .X(_009_)
  );
  sky130_fd_sc_hd__and2_2 _204_ (
    .A(RST_N),
    .B(fp32_in_fp_in[30]),
    .X(_036_)
  );
  sky130_fd_sc_hd__buf_1 _205_ (
    .A(_036_),
    .X(_010_)
  );
  sky130_fd_sc_hd__and2_2 _206_ (
    .A(RST_N),
    .B(fp32_in_fp_in[31]),
    .X(_037_)
  );
  sky130_fd_sc_hd__buf_1 _207_ (
    .A(_037_),
    .X(_011_)
  );
  sky130_fd_sc_hd__xnor2_2 _208_ (
    .A(\rg_fp32[27] ),
    .B(\rg_bias[4] ),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor2_2 _209_ (
    .A(\rg_fp32[25] ),
    .B(\rg_bias[2] ),
    .Y(_039_)
  );
  sky130_fd_sc_hd__xor2_2 _210_ (
    .A(\rg_fp32[24] ),
    .B(\rg_bias[1] ),
    .X(_040_)
  );
  sky130_fd_sc_hd__or2_2 _211_ (
    .A(\rg_fp32[23] ),
    .B(\_128_MINUS_0_CONCAT_rg_bias_0_MINUS_4___d11[0] ),
    .X(_041_)
  );
  sky130_fd_sc_hd__and2_2 _212_ (
    .A(\rg_fp32[24] ),
    .B(\rg_bias[1] ),
    .X(_042_)
  );
  sky130_fd_sc_hd__a21oi_2 _213_ (
    .A1(_040_),
    .A2(_041_),
    .B1(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_2 _214_ (
    .A(\rg_fp32[25] ),
    .B(\rg_bias[2] ),
    .Y(_044_)
  );
  sky130_fd_sc_hd__o21a_2 _215_ (
    .A1(_039_),
    .A2(_043_),
    .B1(_044_),
    .X(_045_)
  );
  sky130_fd_sc_hd__nor2_2 _216_ (
    .A(\rg_fp32[26] ),
    .B(\rg_bias[3] ),
    .Y(_046_)
  );
  sky130_fd_sc_hd__and2_2 _217_ (
    .A(\rg_fp32[26] ),
    .B(\rg_bias[3] ),
    .X(_047_)
  );
  sky130_fd_sc_hd__o21ba_2 _218_ (
    .A1(_045_),
    .A2(_046_),
    .B1_N(_047_),
    .X(_048_)
  );
  sky130_fd_sc_hd__xor2_2 _219_ (
    .A(_038_),
    .B(_048_),
    .X(_049_)
  );
  sky130_fd_sc_hd__and2_2 _220_ (
    .A(\rg_fp32[25] ),
    .B(\rg_bias[2] ),
    .X(_050_)
  );
  sky130_fd_sc_hd__nor2_2 _221_ (
    .A(_050_),
    .B(_039_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__xor2_2 _222_ (
    .A(_051_),
    .B(_043_),
    .X(_052_)
  );
  sky130_fd_sc_hd__nor2_2 _223_ (
    .A(_047_),
    .B(_046_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__xor2_2 _224_ (
    .A(_045_),
    .B(_053_),
    .X(_054_)
  );
  sky130_fd_sc_hd__or2b_2 _225_ (
    .A(\rg_fp32[23] ),
    .B_N(\_128_MINUS_0_CONCAT_rg_bias_0_MINUS_4___d11[0] ),
    .X(_055_)
  );
  sky130_fd_sc_hd__or2b_2 _226_ (
    .A(\_128_MINUS_0_CONCAT_rg_bias_0_MINUS_4___d11[0] ),
    .B_N(\rg_fp32[23] ),
    .X(_056_)
  );
  sky130_fd_sc_hd__nand2_2 _227_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__xnor2_2 _228_ (
    .A(_040_),
    .B(_041_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__or2_2 _229_ (
    .A(_057_),
    .B(_058_),
    .X(_059_)
  );
  sky130_fd_sc_hd__nand2_2 _230_ (
    .A(\rg_fp32[21] ),
    .B(\rg_fp32[22] ),
    .Y(_060_)
  );
  sky130_fd_sc_hd__or4_2 _231_ (
    .A(_052_),
    .B(_054_),
    .C(_059_),
    .D(_060_),
    .X(_061_)
  );
  sky130_fd_sc_hd__and2_2 _232_ (
    .A(\rg_bias[1] ),
    .B(\_128_MINUS_0_CONCAT_rg_bias_0_MINUS_4___d11[0] ),
    .X(_062_)
  );
  sky130_fd_sc_hd__and3_2 _233_ (
    .A(\rg_bias[3] ),
    .B(\rg_bias[2] ),
    .C(_062_),
    .X(_063_)
  );
  sky130_fd_sc_hd__and3_2 _234_ (
    .A(\rg_bias[5] ),
    .B(\rg_bias[4] ),
    .C(_063_),
    .X(_064_)
  );
  sky130_fd_sc_hd__a21oi_2 _235_ (
    .A1(\rg_bias[4] ),
    .A2(_063_),
    .B1(\rg_bias[5] ),
    .Y(_065_)
  );
  sky130_fd_sc_hd__or3_2 _236_ (
    .A(\rg_fp32[28] ),
    .B(_064_),
    .C(_065_),
    .X(_066_)
  );
  sky130_fd_sc_hd__o21ai_2 _237_ (
    .A1(_064_),
    .A2(_065_),
    .B1(\rg_fp32[28] ),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_2 _238_ (
    .A(_066_),
    .B(_067_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__inv_2 _239_ (
    .A(\rg_fp32[27] ),
    .Y(_069_)
  );
  sky130_fd_sc_hd__xnor2_2 _240_ (
    .A(\rg_bias[4] ),
    .B(_063_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__xnor2_2 _241_ (
    .A(_069_),
    .B(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__a211o_2 _242_ (
    .A1(_049_),
    .A2(_061_),
    .B1(_068_),
    .C1(_071_),
    .X(_072_)
  );
  sky130_fd_sc_hd__o21ai_2 _243_ (
    .A1(_069_),
    .A2(_070_),
    .B1(_067_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__a21o_2 _244_ (
    .A1(\rg_bias[4] ),
    .A2(_063_),
    .B1(\rg_bias[5] ),
    .X(_074_)
  );
  sky130_fd_sc_hd__o21a_2 _245_ (
    .A1(\rg_fp32[29] ),
    .A2(_074_),
    .B1(\rg_fp32[30] ),
    .X(_075_)
  );
  sky130_fd_sc_hd__a21oi_2 _246_ (
    .A1(_066_),
    .A2(_073_),
    .B1(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__a21oi_2 _247_ (
    .A1(\rg_fp32[29] ),
    .A2(_074_),
    .B1(\rg_fp32[30] ),
    .Y(_077_)
  );
  sky130_fd_sc_hd__a21oi_2 _248_ (
    .A1(_072_),
    .A2(_076_),
    .B1(_077_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__inv_2 _249_ (
    .A(\rg_bias[1] ),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor3_2 _250_ (
    .A(\rg_bias[2] ),
    .B(\rg_bias[1] ),
    .C(\_128_MINUS_0_CONCAT_rg_bias_0_MINUS_4___d11[0] ),
    .Y(_080_)
  );
  sky130_fd_sc_hd__o21a_2 _251_ (
    .A1(\rg_bias[1] ),
    .A2(\_128_MINUS_0_CONCAT_rg_bias_0_MINUS_4___d11[0] ),
    .B1(\rg_bias[2] ),
    .X(_081_)
  );
  sky130_fd_sc_hd__o31ai_2 _252_ (
    .A1(\rg_bias[2] ),
    .A2(\rg_bias[1] ),
    .A3(\_128_MINUS_0_CONCAT_rg_bias_0_MINUS_4___d11[0] ),
    .B1(\rg_bias[3] ),
    .Y(_082_)
  );
  sky130_fd_sc_hd__or4_2 _253_ (
    .A(\rg_bias[3] ),
    .B(\rg_bias[2] ),
    .C(\rg_bias[1] ),
    .D(\_128_MINUS_0_CONCAT_rg_bias_0_MINUS_4___d11[0] ),
    .X(_083_)
  );
  sky130_fd_sc_hd__buf_1 _254_ (
    .A(_083_),
    .X(_084_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _255_ (
    .A1_N(_080_),
    .A2_N(_081_),
    .B1(_082_),
    .B2(_084_),
    .X(_085_)
  );
  sky130_fd_sc_hd__xor2_2 _256_ (
    .A(\rg_bias[4] ),
    .B(_084_),
    .X(_086_)
  );
  sky130_fd_sc_hd__a211oi_2 _257_ (
    .A1(_079_),
    .A2(\_128_MINUS_0_CONCAT_rg_bias_0_MINUS_4___d11[0] ),
    .B1(_085_),
    .C1(_086_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__o21ai_2 _258_ (
    .A1(\rg_bias[4] ),
    .A2(_084_),
    .B1(\rg_bias[5] ),
    .Y(_088_)
  );
  sky130_fd_sc_hd__or3_2 _259_ (
    .A(\rg_bias[5] ),
    .B(\rg_bias[4] ),
    .C(_084_),
    .X(_089_)
  );
  sky130_fd_sc_hd__nand2_2 _260_ (
    .A(_088_),
    .B(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__xor2_2 _261_ (
    .A(\rg_fp32[28] ),
    .B(_090_),
    .X(_091_)
  );
  sky130_fd_sc_hd__and2_2 _262_ (
    .A(_087_),
    .B(_091_),
    .X(_092_)
  );
  sky130_fd_sc_hd__nor2_2 _263_ (
    .A(_087_),
    .B(_091_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__xor2_2 _264_ (
    .A(\rg_fp32[29] ),
    .B(_089_),
    .X(_094_)
  );
  sky130_fd_sc_hd__nand2_2 _265_ (
    .A(_090_),
    .B(_087_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__xnor2_2 _266_ (
    .A(_094_),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__a21oi_2 _267_ (
    .A1(_079_),
    .A2(\_128_MINUS_0_CONCAT_rg_bias_0_MINUS_4___d11[0] ),
    .B1(_085_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__xnor2_2 _268_ (
    .A(\rg_fp32[27] ),
    .B(_086_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor2_2 _269_ (
    .A(_097_),
    .B(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__and2_2 _270_ (
    .A(_055_),
    .B(_056_),
    .X(_100_)
  );
  sky130_fd_sc_hd__a2111o_2 _271_ (
    .A1(_097_),
    .A2(_098_),
    .B1(\rg_fp32[30] ),
    .C1(_040_),
    .D1(_100_),
    .X(_101_)
  );
  sky130_fd_sc_hd__or4_2 _272_ (
    .A(_052_),
    .B(_054_),
    .C(_099_),
    .D(_101_),
    .X(_102_)
  );
  sky130_fd_sc_hd__or4_2 _273_ (
    .A(_092_),
    .B(_093_),
    .C(_096_),
    .D(_102_),
    .X(_103_)
  );
  sky130_fd_sc_hd__nor2_2 _274_ (
    .A(\rg_fp32[22] ),
    .B(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nor3_2 _275_ (
    .A(_052_),
    .B(_054_),
    .C(_059_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__xor2_2 _276_ (
    .A(\rg_fp32[29] ),
    .B(_064_),
    .X(_106_)
  );
  sky130_fd_sc_hd__nor2_2 _277_ (
    .A(\rg_fp32[30] ),
    .B(_071_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand4_2 _278_ (
    .A(_068_),
    .B(_105_),
    .C(_106_),
    .D(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a21o_2 _279_ (
    .A1(\rg_fp32[21] ),
    .A2(\rg_fp32[20] ),
    .B1(\rg_fp32[22] ),
    .X(_109_)
  );
  sky130_fd_sc_hd__inv_2 _280_ (
    .A(\rg_fp32[30] ),
    .Y(_110_)
  );
  sky130_fd_sc_hd__o211a_2 _281_ (
    .A1(\rg_fp32[28] ),
    .A2(\rg_bias[5] ),
    .B1(\rg_fp32[29] ),
    .C1(_110_),
    .X(_111_)
  );
  sky130_fd_sc_hd__a21bo_2 _282_ (
    .A1(\rg_fp32[28] ),
    .A2(\rg_bias[5] ),
    .B1_N(_111_),
    .X(_112_)
  );
  sky130_fd_sc_hd__and3_2 _283_ (
    .A(_051_),
    .B(_040_),
    .C(_053_),
    .X(_113_)
  );
  sky130_fd_sc_hd__or4b_2 _284_ (
    .A(_038_),
    .B(_100_),
    .C(_112_),
    .D_N(_113_),
    .X(_114_)
  );
  sky130_fd_sc_hd__nor2_2 _285_ (
    .A(_109_),
    .B(_114_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__a41o_2 _286_ (
    .A1(_068_),
    .A2(_105_),
    .A3(_106_),
    .A4(_107_),
    .B1(_115_),
    .X(_116_)
  );
  sky130_fd_sc_hd__o31a_2 _287_ (
    .A1(\rg_fp32[21] ),
    .A2(\rg_fp32[22] ),
    .A3(_108_),
    .B1(_116_),
    .X(_117_)
  );
  sky130_fd_sc_hd__nor2_2 _288_ (
    .A(_085_),
    .B(_086_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__and2b_2 _289_ (
    .A_N(_088_),
    .B(_118_),
    .X(_119_)
  );
  sky130_fd_sc_hd__xor2_2 _290_ (
    .A(_118_),
    .B(_090_),
    .X(_120_)
  );
  sky130_fd_sc_hd__o22a_2 _291_ (
    .A1(\rg_fp32[29] ),
    .A2(_119_),
    .B1(_120_),
    .B2(\rg_fp32[28] ),
    .X(_121_)
  );
  sky130_fd_sc_hd__xor2_2 _292_ (
    .A(_085_),
    .B(_086_),
    .X(_122_)
  );
  sky130_fd_sc_hd__and2_2 _293_ (
    .A(\rg_fp32[27] ),
    .B(_122_),
    .X(_123_)
  );
  sky130_fd_sc_hd__a21oi_2 _294_ (
    .A1(\rg_fp32[28] ),
    .A2(_120_),
    .B1(_123_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__or3_2 _295_ (
    .A(\rg_bias[3] ),
    .B(_080_),
    .C(_081_),
    .X(_125_)
  );
  sky130_fd_sc_hd__and3_2 _296_ (
    .A(\rg_fp32[26] ),
    .B(_085_),
    .C(_125_),
    .X(_126_)
  );
  sky130_fd_sc_hd__nor2_2 _297_ (
    .A(\rg_bias[1] ),
    .B(\_128_MINUS_0_CONCAT_rg_bias_0_MINUS_4___d11[0] ),
    .Y(_127_)
  );
  sky130_fd_sc_hd__o31ai_2 _298_ (
    .A1(\rg_fp32[24] ),
    .A2(_127_),
    .A3(_062_),
    .B1(_055_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__o21ai_2 _299_ (
    .A1(_080_),
    .A2(_081_),
    .B1(\rg_fp32[25] ),
    .Y(_129_)
  );
  sky130_fd_sc_hd__or3_2 _300_ (
    .A(\rg_fp32[25] ),
    .B(_080_),
    .C(_081_),
    .X(_130_)
  );
  sky130_fd_sc_hd__nand2_2 _301_ (
    .A(_129_),
    .B(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__o21ai_2 _302_ (
    .A1(_127_),
    .A2(_062_),
    .B1(\rg_fp32[24] ),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand4b_2 _303_ (
    .A_N(_128_),
    .B(_056_),
    .C(_131_),
    .D(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a21o_2 _304_ (
    .A1(_085_),
    .A2(_125_),
    .B1(\rg_fp32[26] ),
    .X(_134_)
  );
  sky130_fd_sc_hd__o21a_2 _305_ (
    .A1(\rg_fp32[27] ),
    .A2(_122_),
    .B1(_134_),
    .X(_135_)
  );
  sky130_fd_sc_hd__or3b_2 _306_ (
    .A(_126_),
    .B(_133_),
    .C_N(_135_),
    .X(_136_)
  );
  sky130_fd_sc_hd__a211oi_2 _307_ (
    .A1(\rg_fp32[29] ),
    .A2(_119_),
    .B1(_136_),
    .C1(\rg_fp32[30] ),
    .Y(_137_)
  );
  sky130_fd_sc_hd__xor2_2 _308_ (
    .A(\rg_fp32[21] ),
    .B(\rg_fp32[20] ),
    .X(_138_)
  );
  sky130_fd_sc_hd__or2_2 _309_ (
    .A(\rg_fp32[28] ),
    .B(_090_),
    .X(_139_)
  );
  sky130_fd_sc_hd__nand2_2 _310_ (
    .A(_132_),
    .B(_128_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a21bo_2 _311_ (
    .A1(_084_),
    .A2(_082_),
    .B1_N(\rg_fp32[26] ),
    .X(_141_)
  );
  sky130_fd_sc_hd__and2_2 _312_ (
    .A(_129_),
    .B(_141_),
    .X(_142_)
  );
  sky130_fd_sc_hd__a21bo_2 _313_ (
    .A1(_130_),
    .A2(_140_),
    .B1_N(_142_),
    .X(_143_)
  );
  sky130_fd_sc_hd__nand3b_2 _314_ (
    .A_N(\rg_fp32[26] ),
    .B(_084_),
    .C(_082_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__a21boi_2 _315_ (
    .A1(_069_),
    .A2(_086_),
    .B1_N(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nor2_2 _316_ (
    .A(_069_),
    .B(_086_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__a221o_2 _317_ (
    .A1(\rg_fp32[28] ),
    .A2(_090_),
    .B1(_143_),
    .B2(_145_),
    .C1(_146_),
    .X(_147_)
  );
  sky130_fd_sc_hd__a41o_2 _318_ (
    .A1(\rg_fp32[29] ),
    .A2(_089_),
    .A3(_139_),
    .A4(_147_),
    .B1(\rg_fp32[30] ),
    .X(_148_)
  );
  sky130_fd_sc_hd__a32o_2 _319_ (
    .A1(_121_),
    .A2(_124_),
    .A3(_137_),
    .B1(_138_),
    .B2(_148_),
    .X(_149_)
  );
  sky130_fd_sc_hd__and2_2 _320_ (
    .A(_130_),
    .B(_144_),
    .X(_150_)
  );
  sky130_fd_sc_hd__a221o_2 _321_ (
    .A1(_142_),
    .A2(_150_),
    .B1(_131_),
    .B2(_140_),
    .C1(_126_),
    .X(_151_)
  );
  sky130_fd_sc_hd__a221o_2 _322_ (
    .A1(\rg_fp32[28] ),
    .A2(_120_),
    .B1(_135_),
    .B2(_151_),
    .C1(_123_),
    .X(_152_)
  );
  sky130_fd_sc_hd__a221o_2 _323_ (
    .A1(\rg_fp32[29] ),
    .A2(_119_),
    .B1(_121_),
    .B2(_152_),
    .C1(\rg_fp32[30] ),
    .X(_153_)
  );
  sky130_fd_sc_hd__and2_2 _324_ (
    .A(RST_N),
    .B(_153_),
    .X(_154_)
  );
  sky130_fd_sc_hd__o41a_2 _325_ (
    .A1(_078_),
    .A2(_104_),
    .A3(_117_),
    .A4(_149_),
    .B1(_154_),
    .X(_012_)
  );
  sky130_fd_sc_hd__buf_1 _326_ (
    .A(_078_),
    .X(_155_)
  );
  sky130_fd_sc_hd__mux2_2 _327_ (
    .A0(\rg_fp32[22] ),
    .A1(_116_),
    .S(_103_),
    .X(_156_)
  );
  sky130_fd_sc_hd__buf_1 _328_ (
    .A(_148_),
    .X(_157_)
  );
  sky130_fd_sc_hd__nand3_2 _329_ (
    .A(\rg_fp32[21] ),
    .B(\rg_fp32[20] ),
    .C(\rg_fp32[22] ),
    .Y(_158_)
  );
  sky130_fd_sc_hd__and3_2 _330_ (
    .A(_109_),
    .B(_157_),
    .C(_158_),
    .X(_159_)
  );
  sky130_fd_sc_hd__buf_1 _331_ (
    .A(_154_),
    .X(_160_)
  );
  sky130_fd_sc_hd__o31a_2 _332_ (
    .A1(_155_),
    .A2(_156_),
    .A3(_159_),
    .B1(_160_),
    .X(_013_)
  );
  sky130_fd_sc_hd__or2_2 _333_ (
    .A(_057_),
    .B(_158_),
    .X(_161_)
  );
  sky130_fd_sc_hd__nand2_2 _334_ (
    .A(_057_),
    .B(_158_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__inv_2 _335_ (
    .A(_114_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a32o_2 _336_ (
    .A1(_157_),
    .A2(_161_),
    .A3(_162_),
    .B1(_163_),
    .B2(_109_),
    .X(_164_)
  );
  sky130_fd_sc_hd__o21a_2 _337_ (
    .A1(_155_),
    .A2(_164_),
    .B1(_160_),
    .X(_014_)
  );
  sky130_fd_sc_hd__or2_2 _338_ (
    .A(_058_),
    .B(_161_),
    .X(_165_)
  );
  sky130_fd_sc_hd__nand2_2 _339_ (
    .A(_058_),
    .B(_161_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__and3_2 _340_ (
    .A(_157_),
    .B(_165_),
    .C(_166_),
    .X(_167_)
  );
  sky130_fd_sc_hd__o21a_2 _341_ (
    .A1(_155_),
    .A2(_167_),
    .B1(_160_),
    .X(_015_)
  );
  sky130_fd_sc_hd__or2_2 _342_ (
    .A(_052_),
    .B(_165_),
    .X(_168_)
  );
  sky130_fd_sc_hd__nand2_2 _343_ (
    .A(_052_),
    .B(_165_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__and3_2 _344_ (
    .A(_157_),
    .B(_168_),
    .C(_169_),
    .X(_170_)
  );
  sky130_fd_sc_hd__o21a_2 _345_ (
    .A1(_155_),
    .A2(_170_),
    .B1(_160_),
    .X(_016_)
  );
  sky130_fd_sc_hd__or3_2 _346_ (
    .A(_052_),
    .B(_054_),
    .C(_165_),
    .X(_171_)
  );
  sky130_fd_sc_hd__nand2_2 _347_ (
    .A(_054_),
    .B(_168_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__and3_2 _348_ (
    .A(_157_),
    .B(_171_),
    .C(_172_),
    .X(_173_)
  );
  sky130_fd_sc_hd__o21a_2 _349_ (
    .A1(_155_),
    .A2(_173_),
    .B1(_160_),
    .X(_017_)
  );
  sky130_fd_sc_hd__and2_2 _350_ (
    .A(_049_),
    .B(_171_),
    .X(_174_)
  );
  sky130_fd_sc_hd__nor2_2 _351_ (
    .A(_049_),
    .B(_171_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__o21a_2 _352_ (
    .A1(_174_),
    .A2(_175_),
    .B1(_157_),
    .X(_176_)
  );
  sky130_fd_sc_hd__o21a_2 _353_ (
    .A1(_155_),
    .A2(_176_),
    .B1(_160_),
    .X(_018_)
  );
  sky130_fd_sc_hd__and2_2 _354_ (
    .A(RST_N),
    .B(bias_in_bias[0]),
    .X(_177_)
  );
  sky130_fd_sc_hd__buf_1 _355_ (
    .A(_177_),
    .X(_019_)
  );
  sky130_fd_sc_hd__and2_2 _356_ (
    .A(RST_N),
    .B(bias_in_bias[1]),
    .X(_178_)
  );
  sky130_fd_sc_hd__buf_1 _357_ (
    .A(_178_),
    .X(_020_)
  );
  sky130_fd_sc_hd__and2_2 _358_ (
    .A(RST_N),
    .B(bias_in_bias[2]),
    .X(_179_)
  );
  sky130_fd_sc_hd__buf_1 _359_ (
    .A(_179_),
    .X(_021_)
  );
  sky130_fd_sc_hd__and2_2 _360_ (
    .A(RST_N),
    .B(bias_in_bias[3]),
    .X(_180_)
  );
  sky130_fd_sc_hd__buf_1 _361_ (
    .A(_180_),
    .X(_022_)
  );
  sky130_fd_sc_hd__and2_2 _362_ (
    .A(RST_N),
    .B(bias_in_bias[4]),
    .X(_181_)
  );
  sky130_fd_sc_hd__buf_1 _363_ (
    .A(_181_),
    .X(_023_)
  );
  sky130_fd_sc_hd__and2_2 _364_ (
    .A(RST_N),
    .B(bias_in_bias[5]),
    .X(_182_)
  );
  sky130_fd_sc_hd__buf_1 _365_ (
    .A(_182_),
    .X(_024_)
  );
  sky130_fd_sc_hd__and2_2 _366_ (
    .A(RST_N),
    .B(\rg_cfloat152$D_IN[7] ),
    .X(_183_)
  );
  sky130_fd_sc_hd__buf_1 _367_ (
    .A(_183_),
    .X(_025_)
  );
  sky130_fd_sc_hd__dfxtp_2 _368_ (
    .CLK(CLK),
    .D(_000_),
    .Q(\rg_fp32[20] )
  );
  sky130_fd_sc_hd__dfxtp_2 _369_ (
    .CLK(CLK),
    .D(_001_),
    .Q(\rg_fp32[21] )
  );
  sky130_fd_sc_hd__dfxtp_2 _370_ (
    .CLK(CLK),
    .D(_002_),
    .Q(\rg_fp32[22] )
  );
  sky130_fd_sc_hd__dfxtp_2 _371_ (
    .CLK(CLK),
    .D(_003_),
    .Q(\rg_fp32[23] )
  );
  sky130_fd_sc_hd__dfxtp_2 _372_ (
    .CLK(CLK),
    .D(_004_),
    .Q(\rg_fp32[24] )
  );
  sky130_fd_sc_hd__dfxtp_2 _373_ (
    .CLK(CLK),
    .D(_005_),
    .Q(\rg_fp32[25] )
  );
  sky130_fd_sc_hd__dfxtp_2 _374_ (
    .CLK(CLK),
    .D(_006_),
    .Q(\rg_fp32[26] )
  );
  sky130_fd_sc_hd__dfxtp_2 _375_ (
    .CLK(CLK),
    .D(_007_),
    .Q(\rg_fp32[27] )
  );
  sky130_fd_sc_hd__dfxtp_2 _376_ (
    .CLK(CLK),
    .D(_008_),
    .Q(\rg_fp32[28] )
  );
  sky130_fd_sc_hd__dfxtp_2 _377_ (
    .CLK(CLK),
    .D(_009_),
    .Q(\rg_fp32[29] )
  );
  sky130_fd_sc_hd__dfxtp_2 _378_ (
    .CLK(CLK),
    .D(_010_),
    .Q(\rg_fp32[30] )
  );
  sky130_fd_sc_hd__dfxtp_2 _379_ (
    .CLK(CLK),
    .D(_011_),
    .Q(\rg_cfloat152$D_IN[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _380_ (
    .CLK(CLK),
    .D(_012_),
    .Q(cfloat152_out[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _381_ (
    .CLK(CLK),
    .D(_013_),
    .Q(cfloat152_out[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _382_ (
    .CLK(CLK),
    .D(_014_),
    .Q(cfloat152_out[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _383_ (
    .CLK(CLK),
    .D(_015_),
    .Q(cfloat152_out[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _384_ (
    .CLK(CLK),
    .D(_016_),
    .Q(cfloat152_out[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _385_ (
    .CLK(CLK),
    .D(_017_),
    .Q(cfloat152_out[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _386_ (
    .CLK(CLK),
    .D(_018_),
    .Q(cfloat152_out[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _387_ (
    .CLK(CLK),
    .D(_019_),
    .Q(\_128_MINUS_0_CONCAT_rg_bias_0_MINUS_4___d11[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _388_ (
    .CLK(CLK),
    .D(_020_),
    .Q(\rg_bias[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _389_ (
    .CLK(CLK),
    .D(_021_),
    .Q(\rg_bias[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _390_ (
    .CLK(CLK),
    .D(_022_),
    .Q(\rg_bias[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _391_ (
    .CLK(CLK),
    .D(_023_),
    .Q(\rg_bias[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _392_ (
    .CLK(CLK),
    .D(_024_),
    .Q(\rg_bias[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _393_ (
    .CLK(CLK),
    .D(_025_),
    .Q(cfloat152_out[7])
  );
endmodule
